### ISSUE TITLE
cannot load libart.so

### ISSUE THREAD

**Issue by bala-saptanglabs** [android/ndk-samples#1063]
i tried loading libart.so with dlopen it worked in  api (21 - 23) but in **api 24+** it is throwinng error file not found, 
i also tried loading libm.so which is in same location (/system/lib/) , it worked for api 24, and 
after android 10 location of libart.so is changed (/apex/com.android.art/lib64/) , is there any workaround needed to load this libart.so?

**Comment by bala-saptanglabs** [comment]
i guess it was made as private library ,[reference]( https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#private-api-enforced-for-api-level-24)

**Comment by DanAlbert** [comment]
It's always been a private library.

What are you actually trying to do?

**Comment by bala-murugan-dev** [comment]
can i able to detect jdwp handshake and stop it  (anti debugging)

**Comment by DanAlbert** [comment]
There's no API for that, no, and it's not a topic I know anything about (I work on open source, so stopping people from debugging has never been something I've needed), so I'm don't have any advice to offer.
