### ISSUE TITLE
What happened to the ndkports maven repo?

### ISSUE THREAD

**Issue by shamilovtim** [android/ndk-samples#1068]
In the [ndkports maven repo](https://mvnrepository.com/artifact/com.android.ndk.thirdparty) AARs have not been receiving updates since 2022. This is despite many of these having activity and updates including openssl. There's no migration guide specified to moving to a different repository or obtaining any of the artifacts a different way. Could anyone please advise what the best way of getting the new openSSL aars is?

I saw the following [comment](https://issuetracker.google.com/issues/173551290) on the issue tracker:
> You don't have to publish curl. Curl is already offered on maven

But since curl is no longer receiving updates on maven, what are we supposed to do now?

**Comment by DanAlbert** [comment]
Not really the place for ndkports, but idk where else to direct you (they're still beta, and part of that is that we don't have support systems up for them yet).

This is why all of those are still labeled as "beta". We've never had the bandwidth to set up automated testing for them, and without that staying on top of updates is also something we can't afford.

For the time being, it seems vcpkg has curl, and not openssl but does have boringssl: https://github.com/microsoft/vcpkg/tree/master/ports. vcpkg can produce AARs as well, so the only difference between getting packages from there is the distribution method and that the vcpkg corpus is up to date (I belive they have significant community support, whereas ndkports has a tiny fraction of me).

If that doesn't work, you can clone the ndkports repo, update the libraries you need, and publish those AARs somewhere that you can use them. It's always been a goal to make ndkports a published gradle plugin so this would be trivial to integrate into a regular android app build (http://b/173551290), but again, we're bandwidth constrained.
