### ISSUE TITLE
Android NDK 27.0.12077973 no file android_native_app_glue.c

### ISSUE THREAD

**Issue by gitMuscleCode** [android/ndk-samples#1073]
AppData\Local\Android\Sdk\ndk\26.3.11579264\sources\android\native_app_glue r26
![26 3 11579264](https://github.com/user-attachments/assets/715b0bd2-fa5a-49cd-a85f-3a0e793400ee)
AppData\Local\Android\Sdk\ndk\27.0.11902837\sources\android\native_app_glue r27 beta
![27 0 11902837 beta](https://github.com/user-attachments/assets/71b4ea3d-a87f-4a79-b666-fde230170933)
AppData\Local\Android\Sdk\ndk\27.0.12077973\sources\android\native_app_glue r27
![27 0 12077973](https://github.com/user-attachments/assets/82f18c89-a4c5-49d8-8133-6880bd5c964e)

file android_native_app_glue.c in r26 (26.3.11579264)           there is a file in the folder
file android_native_app_glue.c in r27 (27.0.11902837) beta   there is a file in the folder
file android_native_app_glue.c in r27 (27.0.12077973)           there is NO file in the folder

this is a joke?

**Comment by DanAlbert** [comment]
Not really sure what this has to do with the samples, but:

```
$ ls ~/Library/Android/sdk/ndk/27.0.12077973/sources/android/native_app_glue
Android.mk                NOTICE                    android_native_app_glue.c android_native_app_glue.h
```

It looks like you're using Windows. Checking that zip to make sure it isn't just Windows that's broken:

```
$ unzip -l ~/Downloads/android-ndk-r27-windows.zip | grep native_app_glue.c
    17270  07-12-2024 19:42   android-ndk-r27/sources/android/native_app_glue/android_native_app_glue.c
```

It looks like your NDK install didn't complete correctly. Uninstall and re-install?

**Comment by gitMuscleCode** [comment]
> Not really sure what this has to do with the samples, but:
> 
> ```
> $ ls ~/Library/Android/sdk/ndk/27.0.12077973/sources/android/native_app_glue
> Android.mk                NOTICE                    android_native_app_glue.c android_native_app_glue.h
> ```
> 
> It looks like you're using Windows. Checking that zip to make sure it isn't just Windows that's broken:
> 
> ```
> $ unzip -l ~/Downloads/android-ndk-r27-windows.zip | grep native_app_glue.c
>     17270  07-12-2024 19:42   android-ndk-r27/sources/android/native_app_glue/android_native_app_glue.c
> ```
> 
> It looks like your NDK install didn't complete correctly. Uninstall and re-install?

I downloaded it again, everything is ok, probably there was some kind of glitch.
Thanks
