### ISSUE TITLE
add a sample using socket api and runtime permission

### ISSUE THREAD

**Issue by GiantGeorgeGo** [android/ndk-samples#122]
Hi all,

I am trying to create a socket using NDK, here is my code:

```
MY_LOG_INFO("A new TCP server creation on going ... ...");
tcp_socket = socket(PF_INET, SOCK_STREAM,0);
int ret = -1;
if (-1 == tcp_socket) {
    MY_LOG_ERROR("socket creation failure!");
} else {
    ret = set_non_block(tcp_socket);
}
```

but hte error shows：

V/ndk_log ( 1815): Ndk_Socket_Util.h:46A new TCP server creation on going ... ...
V/ndk_log ( 1815): Ndk_Socket_Util.h:50socket creation failure! [13:Permission denied] 

I know it must be SeAndroid, but how to resolve it?

**Comment by proppy** [comment]
@GiantGeorgeGo Programming question like this are better discussed on https://stackoverflow.com/questions/tagged/android-ndk, might be related to a missing permission.

Do you think we should add a sample about using the socket API w/ the correct runtime permission flow?

**Comment by GiantGeorgeGo** [comment]
@proppy Thanks for your advice, maybe I posted this question in the wrong place, but actually, if the sample, that will be a good suggestion.

Thanks anyway!

**Comment by wishma2013** [comment]
@proppy yes. That will be good to have a socket API using sample.

**Comment by ggfan** [comment]
bug bankrupcy: open a new one if this is still needed
