### ISSUE TITLE
Create sample showing how to use soft keyboard

### ISSUE THREAD

**Issue by PaulRashidi** [android/ndk-samples#136]
Please ensure JB, L, and M compatibility or flavors of the sample that are compatible with each.

Per discussion with @proppy.

**Comment by PaulRashidi** [comment]
I tested the pull request code on M-tablet w and w/o physical keyboard, L phone, JB phone. LGTM

**Comment by ggfan** [comment]
closing down the long standing bugs: create a new one if this is still needed
