### ISSUE TITLE
Sample re-org proposal

### ISSUE THREAD

**Issue by proppy** [android/ndk-samples#141]
### Rational

Each NDK samples currently have its own gradle project, as we add new project it becomes harder to discover, browse and maintain individual samples.

I'd like to consolidate the NDK sample into _topics_

Each topic would be one 1 gradle project with multiple modules for apps entrypoints and shared libraries.

Each topic should provide either:
a. a good basis to start a new project around that topic.
b. a exhaustive coverage of the native functionality available for that topic

Pros:
- ease maintenance (less project)
- facilitate code reuse by moving common functionality in libraries
- provide native and java entrypoints
- better discovery by topic
- improve navigation by not requiring developer to open 18 different project to browse all NDK samples

Cons: 
- somewhat hard to copy a single project if it grows to big (nuanced by the introduction of a `Template` project and later proper android studio template).
### Alternative

Alternative could be to:
- A: keep the current organization
  pros: 
  - easy to copy a single sample
    cons: 
  - hard to maintain
  - hard to discover & browse (18 ill named projects to open)
- B: move to a single project project for all the sample,
  pros:
  - only one project to open
    cons: 
  - hard to copy a single sample
  - navigation across all sample might be confusing (hard to correlate library and app modules).
### Proposed organization
- GLES
  - hellogl2 and gles3jni merged #124
  - native-activity and java app module
- Audio
  - consolidated audio sample w/ functionality of echo and native-audio in a library
  - native-activity and java app module
- Video
  - consolidated sample native-codec and native-media
  - native-activity and java app module
- NDK API
  - consolidated plasma sample #133 
    - draw in common library
    - two app module renamed PlasmaAndroidBitmap and PlasmaNativeWindow to make it more explicit which API usage they demonstrate
  - more sample for the API listed in http://developer.android.com/ndk/reference/index.html
- Sensors
  - sensor-graph
  - more sensor sample to come
- Build system
  - two-libs #116 with two app module for static and dynamic library linkage.
  - more gradle build system sample to come
- JNI
  - hello-jni
  - native-softkeyboard
  - more java interop sample to come
- Template
  - minimal project with native-activity and java app module
### Deprecation

I would drop `san-angeles` and `endless-tunnel`: those are nice and complete demo app but I think they are beyond the scope of a sample repository designed to show 1 thing per sample.

/cc @ph0b @ggfan @Whiteseeker @rschiu @DanAlbert @claywilkinson @hak @dturner @gguuss  what do you think?

**Comment by Whiteseeker** [comment]
2 concerns:
[1] Why does people check samples :

   - They want to try all of them ?
   - They want to try one of them ?

I think it's more often the second (You wonder how to do X and you find a
sample that show X.

[2] For new developers, I saw many of them lost when opening a sample
project containing dozens of files and module.
Understanding how the sample work require you to understand how the IDE /
build system work, what is a module, how to express dependencies, and which
file is / is not involved in the compilation of each sample (It's even
worst if we have common modules like native activity, or howie in pro audio
samples for instance).

Apart from that I agree that from my pov it's a less maintenance ^^.

**Comment by proppy** [comment]
@Whiteseeker what if instead of having "abstract" topic like GL, Audio, etc we have "How to do X" topic projects, and we only have the number of modules per project necessary to answer the question.

- topic: how to create an opengl context?
   - HelloGLES (with hellogl2 and gles3jni merged, 2 app module 1 with native-activity the other with GLSurfaceView)
- topic: how to draw bitmap?
   - BitmapVSNativeWindow (1 lib 2 app module: show drawing the same plasma with with AndroidBitmap vs NativeWindow)
- topic: how to get sensor data
   - SensorDemo (1 app module per sensor type)
- topic: how to call a Java function from C++
   - CallJavaJNI (with 1 app module per common call people want to make from C++, ex: toggleSoftInput, Camera, etc).
- ...

What do you think?

**Comment by ggfan** [comment]
NDK is a very broad set of the samples, they cover a whole span of application domains; people want to check out the one thing, may not relate to other thing at all; also if one module has a bug, the rest of the modules could not build anymore, and people have to look into the unrelated module to fix build.  For  this scenarios,  I propose to keep samples independent to each other, specially they do not belong to the same subject at all [sensor vs GL, vs. Audio, vs. video etc]

For sample categories, is it possible to have anther dimension for complexity -- say we could have samples of "hello world" for each domain feature; we also have "intermediate / more advanced " samples to address real professional usage model. They would provide unique value to different audience. If this is feasible, each category could be in its own project, or all "intermediate/advanced" samples in its own new repo.

**Comment by proppy** [comment]
> I propose to keep samples independent to each other, specially they do not belong to the same subject at all [sensor vs GL, vs. Audio, vs. video etc]

I think that's close to what I propose, I was proposing to have one separate project per "category": Sensor, GL, Audio, Video. that show all the aspect of a topic.

> They would provide unique value to different audience. If this is feasible, each category could be in its own project, or all "intermediate/advanced" samples in its own new repo.

Yes, I'd want to keep the android-ndk repo for simple samples that show one thing. Should we decide to keep them, I think complete sample like "san-angeles" and "endless-tunnel" should have their own dedicated repo.

**Comment by ggfan** [comment]
closing long standing bugs
