### ISSUE TITLE
Create a sample demonstrating Trace/Multinetwork API's that were added in android-23.

### ISSUE THREAD

**Issue by hak** [android/ndk-samples#203]
Create a sample demonstrating Trace/Multinetwork API's that were added in android-23.

**Comment by qchong** [comment]
Ping. Any update on this?

**Comment by simonprovost** [comment]
Hello,

[Like that ?](https://github.com/sjfricke/NDK-Socket-IPC/tree/85ff728cdbca6f1426d6a762277269ccbb07bf12) If it's not your target, my bad, i am sorry.

++

**Comment by ggfan** [comment]
that is good there is already something on the web about it. Thank you for pointing out;  that one might be Java side of the usage, but the principal is the same for C/C++ side.  In that sense, it is much lower on necessary to create sample for it.

**Comment by ggfan** [comment]
closing the long standing bugs: please create a new one if this is still needed
