### ISSUE TITLE
Order of calling external native build in AS

### ISSUE THREAD

**Issue by beeender** [android/ndk-samples#284]
This is found during migrating our native build to cmake, PR can be found [here](https://github.com/realm/realm-java/pull/2960)

So I am calling `create_javah` to generate the JNI headers before build since I assume the java classes should be compiled before cmake.

Everything works fine with command line `.gw assemble`.

The problem is when running Android Studio (2.2 beta2) with a clean project, gradle sync will fail with cmake error -- `create_javah` cannot find the class files. By checking the `build/intermediates/classes/debug(release)` folder, classes files have been built yet.

So is there any difference to build with AS? It seems the external native build starts before the java build, is it the expected behaviour?

**Comment by ggfan** [comment]
yes, saw the same thing when doing webp sample: https://github.com/googlesamples/android-ndk/blob/master-cmake/webp/view/build.gradle. So downloading webp lib is out outside everything and force it to execute before other activities; asking expert for more authoritative info about this, wait  a little bit

**Comment by jomof** [comment]
I think the expected way to solve this kind of problem in gradle is to create a task that calls create_javah and then to set up the inter-task dependencies to get the build order right.
Something like this:
project.android.applicationVariants.all { variant ->
    def javaHeadersTaskName = "javaHeaders" + variant.name
    Task javaHeaders = task(javaHeadersTaskName) <<  { println "Generate Java Headers Here" }
    variant.externalNativeBuildTasks[0].dependsOn(javaHeaders)
    javaHeaders.dependsOn(variant.javaCompiler)
}

**Comment by ggfan** [comment]
Hi @beeender,  is @jomof's info enough for you? my guess is that UI need to show native file lists before it opens, so it will need to walk through cmake files etc.  My workaround  is not perfect: it downloads files when Android Studio opens up, so all downloading time are included into Android studio start time, which is not fair to Android Studio. But I like to avoid an error too...

**Comment by beeender** [comment]
@ggfan Gradle has too much magic to me :tongue: 
I tried @jomof 's suggestion but got:
> Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.

is it because of we are building a library project?

Also, if I understand correctly, when AS do gradle sync with cmake, it won't build the native code, but just need to generate the json file to parse the project?

**Comment by beeender** [comment]
Tried something like:
```
android.libraryVariants.all { variant ->
    variant.externalNativeBuildTasks[0].dependsOn(variant.javaCompiler)
}
```
Maybe I misunderstand the point, this won't stop AS from calling cmake when do gradle sync, right?

**Comment by jomof** [comment]
AS must call CMake during gradle sync because it needs to get a model (the
JSON) of source files and flags to display and edit. It doesn't actually
compile any sources though. Are you seeing an error from CMake during sync
phase?

**Comment by ggfan** [comment]
I think this error is happening when android studio trying to populate the source dependencies in UI (happens before compile); while under command line, there is no such step necessary so compile dependency would suffice.

**Comment by ggfan** [comment]
Ok, just found this http://stackoverflow.com/questions/39260293/gradle-task-ordering-issue-in-android-studio/40014071#40014071, same problem

**Comment by sureshjoshi** [comment]
@ggfan @beeender 
I've run into this same problem with the order of the AS build. 

I don't know if it's a valid solution, but it -seems- to work. 

I added this into my gradle file, where my Swig auto-generates java files (same issue with files not existing at the appropriate location at the appropriate time).

```
project.afterEvaluate {
    javaPreCompileDebug.dependsOn externalNativeBuildDebug
}
```
https://github.com/sureshjoshi/android-ndk-swig-example

**Comment by ggfan** [comment]
closing this one, repo if it is still needed
