### ISSUE TITLE
Android Ndk Camera / Basic [Resolution HD provoque lag / Latency]

### ISSUE THREAD

**Issue by simonprovost** [android/ndk-samples#562]
**### Hello,**

> Device Information:
> One Plus 6.
> Android 8.1.0

Recently, i was download Android ndk master exemple and i was working on project (camera/basic).
To speak more about my process with this project i wad added Opencv Native to play with it.

Really good sample to see how NDK plus Camera2 works etc.. However, the default resolution when i launch the sample without changed anything was bad(600 x 480 (it works well like without any latency) ), then i changed it into 800x600 and it works beautifull and no latency or lag.

So, i am here to tell you that in HD (1280 x 720) it was not acceptable.. we can see a lot of lag and latency who provoque like 1seconds or 2seconds after 1 minutes running, and i have not changed anything. i was just added Opencv Native in the project but he doesn't call anywhere.

To conclude, i would say that when i open   Android studio profiler during app running, he say 12 ~ 16 % of cpu was consumed and 40 ~ 55 Mb for the memory of my device..

It is possible that was the conversion YUB into RGB ?
 
I will really grateful if you have anything to tell me about it or to help me.
Thank you Advance.
++

**Comment by ggfan** [comment]
Yeah it would be the color conversion: needs to be done on hardware ( GPU ) to do YUV to RGB conversion for big resolution. Add [Android Hardware Buffer](https://developer.android.com/reference/android/hardware/HardwareBuffer) into it -- use it to share between Gfx and Camera. Having a plan to add AHardwareBuffer/OpenGL for camera sample ( hope someday I could get to it ).

**Comment by simonprovost** [comment]
@ggfan Hello, thank you for this really good and faster answer.

I am agree with you that need to be done on hardware (GPU) to make YUV convert into RGB.
In fact, i am new dev. on Android plateform development, then i need more informations about your "solution", please. I mean, you said that i need **Android hardware buffer** into which ? 

Thank you too again.

**Comment by simonprovost** [comment]
@ggfan In the conversion the second nested boucle for, theses line : 

`   nR = MIN(kMaxChannelValue, MAX(0, nR));
    nG = MIN(kMaxChannelValue, MAX(0, nG));
    nB = MIN(kMaxChannelValue, MAX(0, nB));
`

Cause i think the lag/latency.

To test if it works, i was comment theses lines and the color was not too clearly but we have perfects flow without latency or lags. 

Any Idea's ? I think it was not thoses line which caused the really lag but i tell you this EDIT.

**Comment by simonprovost** [comment]
@ggfan Hello, thank you for this really good and fast answer.

I am agree with you that need to be done on hardware (GPU) to make YUV convert into RGB.
In fact, i am new dev. on Android plateform development, then i need more informations about your "solution", please. I mean, you said that i need Android hardware buffer into which ?

Thank you too again.

### **EDIT 1:**

n the conversion the second nested boucle for, theses line :

nR = MIN(kMaxChannelValue, MAX(0, nR)); nG = MIN(kMaxChannelValue, MAX(0, nG)); nB = MIN(kMaxChannelValue, MAX(0, nB));

Cause i think the lag/latency.

To test if it works, i was comment theses lines and the color was not too clearly but we have perfects flow without latency or lags.

Any Idea's ? I think it was not thoses line which caused the really lag but i tell you this EDIT.

### **EDIT 2:**

I have read the Android Hardware Buffer Documentation, i was made a prototype like that : 

`
void CameraEngine::DrawFrame(void) { 
  if (!cameraReady_ || !yuvReader_) return;
  AImage* image = yuvReader_->GetNextImage();
  if (!image) {
    return;
  }
    int ret;
    void* shared_buffer;

    ANativeWindow_acquire(app_->window);
    ANativeWindow_Buffer buf;
    if (ANativeWindow_lock(app_->window, &buf, nullptr) < 0) {
      yuvReader_->DeleteImage(image);
      return;
  }
    AImage_getHardwareBuffer(image, &h_buffer);


    AHardwareBuffer_describe(h_buffer, &h_buffer_desc);
    LOGI("ANativeWindow_Buffer Size: %d", buf.height * buf.stride * 4);
    LOGI("ANativeWindow_Buffer Size ----->AHardwareBuffer Size: %d", h_buffer_desc.height *
            h_buffer_desc.stride * 4);

    ret = AHardwareBuffer_lock(h_buffer,
                               AHARDWAREBUFFER_USAGE_CPU_WRITE_MASK,
                               -1, // no fence in demo
                               NULL,
                               &shared_buffer);
    if (ret != 0 || !shared_buffer) {
        LOGE("Failed to AHardwareBuffer_lock");
        yuvReader_->DeleteImage(image);
        return;
    }
    memcpy(buf.bits, shared_buffer, ( h_buffer_desc.height * h_buffer_desc.stride));

  yuvReader_->DisplayImage(&buf, image);  // It is a func which made a conversion YUV into RGB.

  ret = AHardwareBuffer_unlock(h_buffer, NULL);
  if (ret != 0) {
      LOGE("Failed to AHardwareBuffer_unlock");
      yuvReader_->DeleteImage(image);
      return;
    }

  ANativeWindow_unlockAndPost(app_->window);
  ANativeWindow_release(app_->window);
}
`
So, the result is same, a lot lag/latency, i have nothing in background during running app.

Thank you advance.

**Comment by ggfan** [comment]
AReadImage needs to use AHardwareBuffer; when image coming back from Camera, use that buffer to  create a texture; add a openGL  shader to sample the texture ( I need to study more about it though ). The key is: pixels stay in the same hardware buffer ( never copied ), and let GPU hardware do the conversion in GL shader.

what you are doing probably make it slower by adding another copying.

**Comment by simonprovost** [comment]
Okok, if you have something like sample or anything else, give it to me please.

Thank you too @ggfan .

**Comment by ggfan** [comment]
closing this one. if you still need some example, you might be able to look at this one:
https://github.com/chadversary/android-ndk-rutabagas
