### ISSUE TITLE
Camera/Basic | How do you placed Blue / Red / Green with your conversion Algorithm ?

### ISSUE THREAD

**Issue by simonprovost** [android/ndk-samples#577]
Opencv Matrice is composed with this method BGR. If you want to draw many red points you need to draw the third entry.

**SYSTEM:**

> Android 7.
> One Plus 6.

**PROJECT:**

> Camera/Basic

I have a huge project which works on other plateforme, i want to export it into Android, i use Camera/Basic Project (GoogleSamples) which works good except one thing but it's not the problem.

On my project i create a matrice like this (cv::Mat ....) and i play with it, i draw on the RED channel my points and i will copy Opencv Matrice data into a ANativeWindow_Buffer which is provide with ANativeWindow_Lock.

Before continue, i would say that these two buffers have same width same height else i will meet a lot crashed but not yet.

In fact, after opencv Mat modified i will make a memcpy on my window buffer :

```cpp

// buff->bits --> provide by ANativeWindow_Lock
// my_Mat.data ---> data which was changed and contain red points for example.
 cv::Size size_mat = my_Mat.size();
 memcpy(buff->bits, my_Mat.data , sizeof(uchar) * my_Mat.step * size_mat.height);
```

And i thought that Camera/Basic project algorithm to convert YUV ---> TO ---> RGB placed a pixel with a correct method but not same as Opencv.

_the convertion algorithm that i spoke can be read on Image_Reader.cpp on every PresentImage*_ 

When i draw my Mat data into ANativeWindow Buffer data, when i show it on my App, i have my drawing but with many different colors instead of only red points then i didn't understand why.

Then, i proven that the algorithm conversion filled theses three channels without same method as Opencv which is BGR (Blue Green Red)

### **My question is, how do you placed it  ?** 

RGB ? BGR ? RRR ? i don't know.
The first :  Blue Green or Red ?
Second : Blue Green or Red ? 
Third : Blue Green or Red ?

Thank you advance and see you soon here i hope.

Best Regards,

**Comment by ggfan** [comment]
referring to code:
```
return 0xff000000 | (nR << 16) | (nG << 8) | nB;
```
By default, now Android is in 32 bit format in   alpha, red, green, blue;  that is single pixel format if you read if out to a 32 bit unsigned integer.  Android is little endian, so inside memory, in the byte order it is
  Blue
  Green
  Red
  Alpha

For buffer geometry ( or format ), you could change it via APIs inside native_window.h:
```
int32_t ANativeWindow_setBuffersGeometry(ANativeWindow* window,
        int32_t width, int32_t height, int32_t format);
```

**Comment by simonprovost** [comment]
@ggfan Thank you for your answer I understand a lot, however, I have a Mat in CV_UC3 which means that the matrice format is in RGB and my buffer geometry is set into RGBA but if I convert my Matrice in RGBA it will make a huge problem on my drawing.

Then I wasn't convert my matrice and I have a little clean drawing, but with many point colors, different instead of only red points, my BuffersGeometry is in RGBA_FORMAT and Opencv Matrice is in RGB same as your method, I don't understand where is the problem right now ?

You said that the byte order in Camera/Basic is B G R same as Opencv and I only draw on Red channel, but I have a lot of others different color points. It is weird, any idea?

**Comment by ggfan** [comment]
you are sure that coming out from OpenCV is RGB format?  confirm that it is packed or not, in memory in byte order, set a breakpoint to examine:
    0
    0
    RED
    0
    0
    RED
if that is the case, you need to insert the alpha channel; if it is 0, 0, RED, Alpha, 0, 0, RED, Alpha format,  then problem is in Android display side.  So first find out which side the problem is. 

You have to try it out and find it out yourself, I do not think this is related to the sample in this repo though.
