### ISSUE TITLE
In the teapot sample, the FPS doesn't show.

### ISSUE THREAD

**Issue by wangjb088** [android/ndk-samples#578]
In the teapot sample, the FPS doesn't show.
![Uploading Screenshot_20180926-224723.jpg…]()

**Comment by ggfan** [comment]
more details please: which device/OS, I could not see the image you uploaded

**Comment by wangjb088** [comment]
I run the sample on Samsung  Galaxy Tab S3, with the Android 7.

**Comment by DanAlbert** [comment]
Was working fine when I ran the sample earlier today.
