### ISSUE TITLE
latency

### ISSUE THREAD

**Issue by alexd555** [android/ndk-samples#580]
Hi,
I made measurements on nexus 4 on the audio-echo project from google ndk examples and I got the following result:

![image](https://user-images.githubusercontent.com/25776246/46602777-d8eedb80-caf9-11e8-81ca-3c4a6defada2.png)

The first line is the recommended parameter of the system(fast path). Could you explain the meaning of the fast path ?

Every time , I multiplied by whole multiples of 10 the buffer size.
My question is: How can I explain the differance of latency ? Why is there no corroletion of the latency ?

Thanks,
Alex

**Comment by ggfan** [comment]
+@philburk for latency question

**Comment by philburk** [comment]
I already answered the question here. 
https://groups.google.com/forum/#!topic/android-ndk/uDSvZ6z9bDQ

**Comment by alexd555** [comment]
Hi,
I asked question again:
How can I explain big difference between first line and second line ?
Can you point me to good acticle that explain meaning of the fast path ?
Thanks,
Alex

‫בתאריך יום ד׳, 10 באוק׳ 2018 ב-20:31 מאת ‪Phil Burk‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by ggfan** [comment]
I think this fast path was part of android low latency initiatives, some related doc could be found [here](https://developer.android.com/ndk/guides/audio/audio-latency#output-latency):
  https://developer.android.com/ndk/guides/audio/audio-latency#output-latency
Under neath the implementation is that:
- frequency
- buffer size
- no signal processing needed
