### ISSUE TITLE
Can not be c++ debugging  in library for Android Studio

### ISSUE THREAD

**Issue by Zhangsongsong** [android/ndk-samples#585]
```java
apply plugin: 'com.android.library'

android {

    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        externalNativeBuild {
            cmake {
                abiFilters 'armeabi-v7a', 'x86'
                cppFlags "-frtti -fexceptions -D__ANDROID__ -std=c++11"
                cFlags "-D__ANDROID__ -DAL_ALEXT_PROTOTYPES -DANDROID"
            }
        }

        //非 app module里面就需要
        ndk {
            moduleName "ffmpeg"
            ldLibs "log"
            abiFilters 'armeabi-v7a', 'x86'

        }
    }

    buildTypes {
        release {
            debuggable false
            jniDebuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            jniDebuggable true

        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
    //非APP module里面就需要
    packagingOptions {
        pickFirst 'lib/armeabi-v7a/libzplay-lib.so'
        pickFirst 'lib/x86/libzplay-lib.so'
    }


}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}

```
what should I do.....(=.=!!)

**Comment by simonprovost** [comment]
Could you write debuggable true even in release mode to see if it is your build variant that causes the problem ? 

Could you check it with another devices Android ? When you run, you run with simple green play logo or green play logo with anchored wheel in background ? 

Regards,

**Comment by Zhangsongsong** [comment]
I try to write debuggable true even in release mode, but not sure. also, I running other projects is debugging.
![image](https://user-images.githubusercontent.com/10123865/47327938-9ef90a00-d6a1-11e8-97ac-de4e56384ca6.png)

**Comment by Zhangsongsong** [comment]
yes

**Comment by simonprovost** [comment]
Something wrong because sometimes I have your problem like right now, but sometimes I can turn on the debug mode with my all breakpoints and other things..

That's weird.. if someone's having a better idea I am interesting about it. 
_Regards_,

**Comment by DanAlbert** [comment]
Sorry no one responded to you sooner. This is the wrong place for Android Studio questions. File a bug against Android Studio by following http://b.android.com. This repo is for the NDK samples.
