### ISSUE TITLE
Latest Android Studio New C++ Project fails to build

### ISSUE THREAD

**Issue by Amandrix** [android/ndk-samples#619]
Just installed android studio, latest version on everything. Created a new native C++ project, and modified absolutely nothing. Yesterday the build worked properly. Today I have this errors and I can't figure out why. Maybe an update happened today and broken everything ?

Build command failed.
Error while executing process D:\AndroidTools\android-sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\Work\Test3\app\src\main\cpp -BD:\Work\Test3\app\.externalNativeBuild\cmake\debug\x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\Work\Test3\app\build\intermediates\cmake\debug\obj\x86_64 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=D:\AndroidTools\android-sdk\ndk-bundle -DCMAKE_CXX_FLAGS= -DCMAKE_TOOLCHAIN_FILE=D:\AndroidTools\android-sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\AndroidTools\android-sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}
-- Check for working C compiler: D:/AndroidTools/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: D:/AndroidTools/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
-- Configuring incomplete, errors occurred!
See also "D:/Work/Test3/app/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeOutput.log".
See also "D:/Work/Test3/app/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeError.log".

CMake Error at D:/AndroidTools/android-sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "D:/AndroidTools/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: D:/Work/Test3/app/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeTmp

  

  Run Build
  Command:"D:\AndroidTools\android-sdk\cmake\3.6.4111459\bin\ninja.exe"
  "cmTC_b514a"

  [1/2] Building C object CMakeFiles/cmTC_b514a.dir/testCCompiler.c.o

  [2/2] Linking C executable cmTC_b514a

  FAILED: cmd.exe /C "cd .  &&
  D:\AndroidTools\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe
  --target=x86_64-none-linux-android21
  --gcc-toolchain=D:/AndroidTools/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64
  --sysroot
  D:/AndroidTools/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot
  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables
  -fstack-protector-strong -no-canonical-prefixes -fno-addrsig
  -Wa,--noexecstack -Wformat -Werror=format-security
  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a
  -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel
  -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments
  -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections
  CMakeFiles/cmTC_b514a.dir/testCCompiler.c.o -o cmTC_b514a -latomic -lm &&
  cd ."

  clang.exe: error: unable to execute command: Couldn't execute program
  'D:/AndroidTools/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin\ld':
  Unknown error (0xC1)

  clang.exe: error: linker command failed with exit code 1 (use -v to see
  invocation)

  ninja: build stopped: subcommand failed.

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt

**Comment by ggfan** [comment]
Not aware there is any update last night.  you reopened the project today with the same android studio version, correct?  ( not like that: Android studio was open all of the time from previous day and today )

**Comment by Amandrix** [comment]
Yes, I just did nothing. Reopened the same project as yesterday. I also created a new project in a different directory (so everything goes from scratch, project creation etc...) and same error.

**Comment by Amandrix** [comment]
Can you create a new native C++ project from android studio, and just try to build it ? But first check for updates, maybe ?

**Comment by ggfan** [comment]
I will check it out.  IDE does have some abnormal with this version(3.3):
  https://developer.android.com/studio/known-issues

however, I am not sure what you saw is the same as the one stated above.

**Comment by Amandrix** [comment]
The wierd thing, is that even if the simple project runs... the cmake and ninja logs are full of errors from the above screenshot.

**Comment by jomof** [comment]
Error 0xC1 on Windows is ERROR_BAD_EXE_FORMAT. Could indicate mismatch
between 32-bits and 64-bits or something like that

**Comment by Amandrix** [comment]
Hmm, but how would you explain that it worked yesterday, and today it doesn't anymore ? I haven't altered the ndk files.

**Comment by jomof** [comment]
What's the content of and Last Modified date of
D:\AndroidTools\android-sdk\ndk-bundle\source.properties?

**Comment by Amandrix** [comment]
Last modified 3 days ago.

Pkg.Desc = Android NDK
Pkg.Revision = 19.0.5232133

**Comment by Amandrix** [comment]
After a closer inspection on logs on all 4 architectures I found out that it fails to compile only for x86_64... hence the output thrown in android studio. For the other 3 platforms, it compiles ok. But I still can't figure out why, yesterday it compiled ok for all 4 platforms.

**Comment by Amandrix** [comment]
Yeah, something is fishy with X86_64... I will take a close inspection in the logs... I have both the logs when it compiled ok, and from today. For example... this is a difference.
File: android_gradle_build_native-lib_x86_64.command.txt
Ok:Executable : D:\AndroidTools\android-sdk\cmake\3.6.4111459\bin\cmake.exe
arguments : 
--build
D:\Work\Test\app\.externalNativeBuild\cmake\debug\x86_64
--target
native-lib
jvmArgs : 


NotOk:Executable : D:\AndroidTools\android-sdk\cmake\3.6.4111459\bin\cmake.exe
arguments : 
-HD:\Work\Test3\app\src\main\cpp
-BD:\Work\Test3\app\.externalNativeBuild\cmake\debug\x86_64
-DANDROID_ABI=x86_64
-DANDROID_PLATFORM=android-21
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\Work\Test3\app\build\intermediates\cmake\debug\obj\x86_64
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=D:\AndroidTools\android-sdk\ndk-bundle
-DCMAKE_CXX_FLAGS=
-DCMAKE_TOOLCHAIN_FILE=D:\AndroidTools\android-sdk\ndk-bundle\build\cmake\android.toolchain.cmake
-DCMAKE_MAKE_PROGRAM=D:\AndroidTools\android-sdk\cmake\3.6.4111459\bin\ninja.exe
-GAndroid Gradle - Ninja
jvmArgs :

**Comment by jomof** [comment]
That actual .exe that is having the problem is:
D:/AndroidTools/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin\ld.exe

**Comment by ggfan** [comment]
I just created a new project on windows 10, it builds and runs fine. Did try to the close the project and re-open the project, also ok. 

But it does not mean there is no issue with Studio, maybe some environment setting is different so prevent me from seeing it. 

probably you could try to clean the project and rebuild it; maybe also try to remove all of those .externativeBuild, build directories under your $project/,  then build it from command line to see how it goes (gradlew.bat assembleDebug ): they seem to be fine for me.

**Comment by Amandrix** [comment]
I've tried literally everything, including restarting windows. Yes jomof, I know that ld.exe is the problem, but who changed it ? I never did anything on my own... I think the last thing to try is to actually delete and re-download the whole ndk.

**Comment by Amandrix** [comment]
At a closer inspection it seems that the .exe is actually unaltered... I have downloaded a seperate standalone NDK, before  I even installed android studio, then I installed it with SDK manager... I compared the 2 .exes and they are identical. I guess it's probably something to do with android studio or graddle. I will dig more and see how can I fix this.

**Comment by ggfan** [comment]
what is your windows OS info?  mine is:
 - windows 10, 64 bit OS, 192G memory
if you could, upload your proj as-is to somewhere?
("gradlew.bat clean assembleDebug" would get more detailed error info? ) 

Nothing specific here excepting guessing around, TBH
