### ISSUE TITLE
'bits/unique_ptr.h' file not found

### ISSUE THREAD

**Issue by gopipeddisetti** [android/ndk-samples#635]
Hello ,
Please help me I am getting below issue 
Build command failed.
Error while executing process /Users/smscountry-imac/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/smscountry-imac/Documents/Telegram/TMessagesProj/jni/Android.mk NDK_APPLICATION_MK=/Users/smscountry-imac/Documents/Telegram/TMessagesProj/jni/Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/Users/smscountry-imac/Documents/Telegram/TMessagesProj/build/intermediates/ndkBuild/afat/debug/obj NDK_LIBS_OUT=/Users/smscountry-imac/Documents/Telegram/TMessagesProj/build/intermediates/ndkBuild/afat/debug/lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j8 /Users/smscountry-imac/Documents/Telegram/TMessagesProj/build/intermediates/ndkBuild/afat/debug/obj/local/arm64-v8a/libtmessages.30.so}
Android NDK: WARNING:/Users/smscountry-imac/Documents/Telegram/TMessagesProj/jni/libtgvoip/Android.mk:flac: LOCAL_LDLIBS is always ignored for static libraries    
Android NDK: WARNING: Unsupported source file extensions in /Users/smscountry-imac/Documents/Telegram/TMessagesProj/jni/libtgvoip/Android.mk for module flac    
Android NDK:   ./exoplayer/libFLAC/windows_unicode_filenames    
[arm64-v8a] Compile++      : tmessages.30 <= gifvideo.cpp
[arm64-v8a] Compile++      : tmessages.30 <= TgNetWrapper.cpp
[arm64-v8a] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/
[arm64-v8a] Compile        : webp <= alpha.c
[arm64-v8a] Compile        : webp <= buffer.c
[arm64-v8a] Compile        : webp <= frame.c
[arm64-v8a] Compile        : webp <= idec.c
[arm64-v8a] Compile        : webp <= io.c
[arm64-v8a] Compile        : webp <= quant.c
[arm64-v8a] Compile        : webp <= vp8.c
[arm64-v8a] Compile        : webp <= vp8l.c
[arm64-v8a] Compile        : webp <= tree.c
[arm64-v8a] Compile        : webp <= webp.c
In file included from /Users/smscountry-imac/Documents/Telegram/TMessagesProj/jni/./TgNetWrapper.cpp:2:
/Users/smscountry-imac/Documents/Telegram/TMessagesProj/jni/tgnet/ApiScheme.h:14:10: fatal error: 'bits/unique_ptr.h' file not found
#include <bits/unique_ptr.h>
         ^~~~~~~~~~~~~~~~~~~
[arm64-v8a] Compile        : webp <= alpha_processing.c
[arm64-v8a] Compile        : webp <= alpha_processing_sse2.c
[arm64-v8a] Compile        : webp <= cpu.c
In file included from /Users/smscountry-imac/Documents/Telegram/TMessagesProj/jni/./gifvideo.cpp:11:
/Users/smscountry-imac/Documents/Telegram/TMessagesProj/jni/tgnet/ConnectionsManager.h:18:10: fatal error: 'bits/unique_ptr.h' file not found
#include <bits/unique_ptr.h>
         ^~~~~~~~~~~~~~~~~~~
[arm64-v8a] Compile        : webp <= dec.c
[arm64-v8a] Compile        : webp <= dec_clip_tables.c
[arm64-v8a] Compile        : webp <= dec_mips32.c
[arm64-v8a] Compile        : webp <= dec_neon.c
[arm64-v8a] Compile        : webp <= dec_sse2.c
[arm64-v8a] Compile        : webp <= enc.c
[arm64-v8a] Compile        : webp <= enc_avx2.c
[arm64-v8a] Compile        : webp <= enc_mips32.c
[arm64-v8a] Compile        : webp <= enc_neon.c
[arm64-v8a] Compile        : webp <= enc_sse2.c
[arm64-v8a] Compile        : webp <= lossless.c
[arm64-v8a] Compile        : webp <= lossless_mips32.c
[arm64-v8a] Compile        : webp <= lossless_neon.c
[arm64-v8a] Compile        : webp <= lossless_sse2.c
[arm64-v8a] Compile        : webp <= upsampling.c
[arm64-v8a] Compile        : webp <= upsampling_neon.c
[arm64-v8a] Compile        : webp <= upsampling_sse2.c
[arm64-v8a] Compile        : webp <= yuv.c
1 error generated.
1 error generated.
[arm64-v8a] Compile        : webp <= yuv_mips32.c
[arm64-v8a] Compile        : webp <= yuv_sse2.c
make: *** [/Users/smscountry-imac/Documents/Telegram/TMessagesProj/build/intermediates/ndkBuild/afat/debug/obj/local/arm64-v8a/objs-debug/tmessages.30/./TgNetWrapper.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [/Users/smscountry-imac/Documents/Telegram/TMessagesProj/build/intermediates/ndkBuild/afat/debug/obj/local/arm64-v8a/objs-debug/tmessages.30/./gifvideo.o] Error 1

**Comment by ggfan** [comment]
this might be NDK related things, that header file belongs to GCC,  you might have to use gcc (set it in TMessagesProj/jni/Application.mk, google "NDK_TOOLCHAIN_VERSION") to build module TMessagesProj.  probably refer to their documentation about how to build that module(I would ndk-build on that module first to get it through then move on). I like to dig to it, but too tied to other things at the moment.
