### ISSUE TITLE
Invalid call to glHint()

### ISSUE THREAD

**Issue by hevrard** [android/ndk-samples#637]
https://github.com/googlesamples/android-ndk/blob/86ceeb248bb20bfffb09330d1a95bcf3e91bb99d/native-activity/app/src/main/cpp/main.cpp#L149

This glHint() call is invalid because GL_PERSPECTIVE_CORRECTION_HINT is not listed in the valid parameter in GLES 3 specification, see https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glHint.xhtml.

**Comment by ggfan** [comment]
This sample is for fixed function pipeline; as you pointed out, might just update it to GL3.2 to use.
( I could not be certain what the reason for the fixed function here as a base, maybe want to have the most device coverage or other reasons )

**Comment by ggfan** [comment]
like to keep one for now, could discuss internally for next round of clean-up
