### ISSUE TITLE
NDK Sample pure C++ without JNI or Java requirement

### ISSUE THREAD

**Issue by bobsort** [android/ndk-samples#644]
Since I couldn't find a single code sample for OpenGL which is purely in C++ without any Java code, 

- I followed native-activity sample code. 
- Removed all motion and sensor code from it. 
- It works as expected
- Next I tried to use code from gles3jni which partially in Java to native-activity to create an OpenGL ES3 application with only C++ code. 

It seems somehow I mange to fail. loadShader function fails. 

I found a few android projects with C++ for GL ES3.0 in other repositories but every single one of them are either for eclipse or android 0.x.x which not only do not load, trying to port it to gradle fails too because of missing libraries in NDK.

I would like to know, is it still possible to create a pure C++ OpenGL? And if yes I appreciate if you could add a sample for it.

**Comment by ggfan** [comment]
I would like to know, is it still possible to create a pure C++ OpenGL?
 - yeah, NativeActivity could be used for GL3 apps.  Once you get the right headers and libs to use for GL3,  and set up the minimum API required, that is enough to build. Yeah at the run time, still need to check platform is supported. 
-  yeah, it is nice to get some samples for more graphics things. For the mean time, if you have some clean errors, you might be able to fix it and move on: you could paste errors here, or other forums

**Comment by wsilly** [comment]
Is there an ndk link on the aarch64 platform?

**Comment by ggfan** [comment]
the question might need to be clarification:
 - if meant with aarch64 host system that runs Android Studio to build, NO there is no such thing. 
 - if meant for the Android ABI, it is there inside NDK.

for those type of questions about the NDK ingredients, please file them at [NDK page](https://github.com/android/ndk)
