### ISSUE TITLE
I'm fairly confident I've discovered a major bug

### ISSUE THREAD

**Issue by cyb3rc0lby** [android/ndk-samples#656]
With NativeActivity itself. I noticed it developing my own apps, so what I did was I opened up the native-activity sample from this repository, and I only made a couple minor changes to demonstrate it. What it does is after you minimize the app, you still see a ghosting effect of what was being rendered, you see it on the main android home screen. The only alteration I made was to have it constantly animating, and I simply alternate the background color every frame between black and white. It happens on two of my tablets, a samsung and a kindle fire. but it doesn't happen on my phone. I've written more about it on stackoverflow and even posted a screenshot: https://stackoverflow.com/questions/57950253/minmizing-opengl-app-while-preserving-egl-context-results-in-huge-problem

I don't know what to do now!

**Comment by dturner** [comment]
Please consider changing your github username. I'm sure you don't mean it but seeing the terms "gentleman suicide" together can trigger painful memories for those people who have been affected by suicide.

**Comment by cyb3rc0lby** [comment]
you're right, it is a bit disturbing, and i've changed it now. but my issue here persists! it's remarkable! have i truly discovered a bug?

**Comment by ggfan** [comment]
could very well be true, thank you! Thank you again for being considerate and changed to a better user name!

are you using this app:  https://github.com/googlesamples/android-ndk/tree/master/native-activity?

**Comment by cyb3rc0lby** [comment]
ggfan: hello and thanks for your time! yes, i opened up that project directly into my android studio, and then i just made a couple of minor changes to demonstrate the problem. i stopped using the engine.animating variable and instead made my own int RENDER global variable. I set it to 0 after I call engine_init_display() and i set it to -1 before i call engine_term_display(). then, for the draw part i just say if (RENDER==0) engine_draw_frame()...and then in the draw function
all i do is this:

    if (engine->display == NULL) {
        // No display.
        return;
    }
    x=1.f-x;
    glClearColor(x,x,x,1.f);
    glClear(GL_COLOR_BUFFER_BIT);
    eglSwapBuffers(engine->display, engine->surface);

then, i minimize the app, and there it is the strong ghosting effects around the edges of my home screen, which decreases over time and turns into a subtle flashing on the entire screen. see the screenshot i posted on stackoverflow to get a better idea of what i mean by ghosting. this happens on two of my tablets but not on my phone.

**Comment by cyb3rc0lby** [comment]
It's doing the same thing with my java project as well, so I guess it's nothing to do with NativeActivity either, and I apologize for not testing this before posting. I sincerely don't know what's going on, however, but now I know it has nothing to do with this project so I guess disregard these posts.
