### ISSUE TITLE
How to export .so file to let the code be used in other project??

### ISSUE THREAD

**Issue by huigesv123** [android/ndk-samples#659]
I code some code in c++ code which is used to make md5 sign with my keys

I want to export so file. How shall I do ?

cmake
android ndk r20
android studio 3.5.1
andoroid 8

**Comment by ggfan** [comment]
you may have a look at the [hello-libs](https://github.com/android/ndk-samples/tree/master/hello-libs) example, module gen-libs.

**Comment by ggfan** [comment]
hope you get your lib exported: the build result from cmakelists.txt is an so file ( striped version ).
