### ISSUE TITLE
Non-exclusive or shared access to opensles recording

### ISSUE THREAD

**Issue by Climax777** [android/ndk-samples#662]
Hi

Does the opensles interface support shared/non-exclusive access to recording the microphone? Similar to AAudio's `AAUDIO_SHARING_MODE_SHARED`?

I need to record audio in the background, while still giving access to other applications to use the microphone.

**Comment by gkasten** [comment]
No, not that I'm aware of.

**Comment by ggfan** [comment]
If you are developing new apps, we recommend to use [Oboe](https://github.com/google/oboe)/[AAudio](https://developer.android.com/ndk/guides/audio/aaudio/aaudio.html) now.
