### ISSUE TITLE
ndk-build  ERROR: Unknown host CPU architecture: aarch64

### ISSUE THREAD

**Issue by wsilly** [android/ndk-samples#663]
有aarch64平台上的ndk吗？
Is there an ndk on the aarch64 platform?

你们只有x64 或 x86的 ndk。
You only have ndk for x64 or x86.

**Comment by ggfan** [comment]
I do not think so.

**Comment by wsilly** [comment]
像这样的android-ndk-r17-linux-aarch64.zip软件包
Android-ndk-r17-linux-aarch64.zip package like this

**Comment by wsilly** [comment]
![image](https://user-images.githubusercontent.com/32908715/68655995-f6e40680-056b-11ea-86f8-e3395cfb134d.png)

**Comment by ggfan** [comment]
This is what you are building for arm64, correct? in that sense, it has been there for a long while:
[arm64-v8a ](https://developer.android.com/ndk/guides/application_mk)

**Comment by wsilly** [comment]
![image](https://user-images.githubusercontent.com/32908715/68732016-f64f7c80-060c-11ea-8580-904c41715258.png)

**Comment by wsilly** [comment]
![image](https://user-images.githubusercontent.com/32908715/68732093-33b40a00-060d-11ea-9b90-35792d33790d.png)
sorry to bother you

**Comment by ggfan** [comment]
俺不太相信你说的 😄： put the link here ( you are looking at the chinese site, right? ), I will download to have a look

**Comment by wsilly** [comment]
Android-ndk-r17-linux-aarch64.zip package like this

**Comment by wsilly** [comment]
arm64 version of the package

**Comment by wsilly** [comment]
Ndk software running on the arm64 liunx system

**Comment by wsilly** [comment]
Sorry! I'm not good at English

**Comment by ggfan** [comment]
[you probably write all comment in one time: 一次写完比较好】
My link:  https://developer.android.com/ndk/downloads/older_releases.html
ndk-17 is also only for x86_64.  Not supported for ARM host, sorry.

**Comment by bighamD** [comment]
楼主找了aarch6-arm的NDK了吗， 怎么解决的，跟你一样的问题

**Comment by bighamD** [comment]
Have u found NDK for aarch-architecture, same error occured like u~~~~

**Comment by ggfan** [comment]
if you set the ABI to:
  armeabi-v7a
  arm64-v8a
  x86
  x86_64

you will be building for your arch, full documentation is [here](https://developer.android.com/ndk/guides/android_mk#target_arch_abi).   Pasting your code here might be easy to see what your situation is.

**Comment by ggfan** [comment]
Oh, if you are looking for the standalone NDK for a specific architecture only,  I, myself, do not support that usage, you might get more info from:  https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md

**Comment by bighamD** [comment]
> Oh, if you are looking for the standalone NDK for a specific architecture only, I, myself, do not support that usage, you might get more info from: https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md

i am a javascript developer, i cant understand the link(https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md) you send. Is  there anyother NDK for specific architecture aarch_64? or how to config .

**Comment by bighamD** [comment]
> if you set the ABI to:
> armeabi-v7a
> arm64-v8a
> x86
> x86_64
> 
> you will be building for your arch, full documentation is [here](https://developer.android.com/ndk/guides/android_mk#target_arch_abi). Pasting your code here might be easy to see what your situation is.

NDK what i use is  android-ndk-r21-linux-x86_64.zip from https://developer.android.com/ndk/downloads?hl=zh-cn,  but it is not for architecture-aarch_64

**Comment by bighamD** [comment]
![image](https://user-images.githubusercontent.com/41603686/80301223-6fb2e400-87d5-11ea-8cde-9151f532e4ad.png)

**Comment by ggfan** [comment]
if you linux on arm64, there is no NDK for it.
