### ISSUE TITLE
ACameraManager_getCameraIdList return weird value(-866653748)

### ISSUE THREAD

**Issue by stereomatchingkiss** [android/ndk-samples#676]
Trying to build an app with Qt5.12.3 and android ndk, but cannot get camera list by "ACameraManager_getCameraIdList".

    Mobile : Sony xperia XA1 Ultra
    Qt: 5.12.3
    NDK : r19c
    minimum target: 24
    maximum target: 28
    Android library link to : libcamera2ndk.so and libmediandk.so, I link to the libs of api 28, not 24(android-28\arch-arm\usr\lib)
    permissions: uses-permission android:name="android.permission.CAMERA"/
    arch : armeabi-v7a
    jdk : jdk1.8.0_201

Extra so files I add into the project

```
contains(ANDROID_TARGET_ARCH, armeabi-v7a) {
    ANDROID_EXTRA_LIBS = \
        C:/Users/yyyy/programs/Qt/android_camera/../../../3rdLibs/Android/android-ndk-r19c-windows-x86_64/android-ndk-r19c/platforms/android-28/arch-arm/usr/lib/libcamera2ndk.so
}
```

Source codes:

```
#include "mainwindow.hpp"
#include <QApplication>

#include <QDebug>

#ifdef Q_OS_ANDROID

#include <android/log.h>

#include <camera/NdkCameraManager.h>

#include <QDebug>
#include <QtAndroid>
#include <QtAndroidExtras>

void myMessageHandler(
        QtMsgType type,
        const QMessageLogContext& context,
        const QString& msg
        )
{
    const char*const applicationName="android_camera";

    QString report=msg;
    if (context.file && !QString(context.file).isEmpty()) {
        report+=" in file ";
        report+=QString(context.file);
        report+=" line ";
        report+=QString::number(context.line);
    }
    if (context.function && !QString(context.function).isEmpty()) {
        report+=+" function ";
        report+=QString(context.function);
    }
    const char*const local=report.toLocal8Bit().constData();
    switch (type) {
    case QtDebugMsg:
        __android_log_write(ANDROID_LOG_DEBUG,applicationName,local);
        break;
    case QtInfoMsg:
        __android_log_write(ANDROID_LOG_INFO,applicationName,local);
        break;
    case QtWarningMsg:
        __android_log_write(ANDROID_LOG_WARN,applicationName,local);
        break;
    case QtCriticalMsg:
        __android_log_write(ANDROID_LOG_ERROR,applicationName,local);
        break;
    case QtFatalMsg:
        __android_log_write(ANDROID_LOG_FATAL,applicationName,local);
        abort();
    }
}

void open_android_camera()
{
    auto result = QtAndroid::checkPermission(QString("android.permission.CAMERA"));
    if(result == QtAndroid::PermissionResult::Denied){
        QtAndroid::PermissionResultMap resultHash =
                QtAndroid::requestPermissionsSync(QStringList({"android.permission.CAMERA"}));
        if(resultHash["android.permission.CAMERA"] == QtAndroid::PermissionResult::Denied){
            qInfo()<<__func__<<"permission deny";
        }else{
            qInfo()<<__func__<<"permission granted";
        }
    }

    qInfo()<<__func__<<"create camera manager";
    ACameraManager *camera_manager_ = ACameraManager_create();
    if(camera_manager_){
        qInfo()<<__func__<<"get camera ids";
        ACameraIdList *camera_ids = nullptr;
        auto const status = ACameraManager_getCameraIdList(camera_manager_, &camera_ids);
        qInfo()<<__func__<<"can get camera ids:"<<(camera_ids != nullptr)<<", status:"<<status;
        switch(status){
        case ACAMERA_OK:
            qInfo()<<__func__<<"ACAMERA_OK";
            break;
        case ACAMERA_ERROR_INVALID_PARAMETER:
            qInfo()<<__func__<<"ACAMERA_ERROR_INVALID_PARAMETER";
            break;
        case ACAMERA_ERROR_CAMERA_DISCONNECTED:
            qInfo()<<__func__<<"ACAMERA_ERROR_CAMERA_DISCONNECTED";
            break;
        case ACAMERA_ERROR_NOT_ENOUGH_MEMORY:
            qInfo()<<__func__<<"ACAMERA_ERROR_NOT_ENOUGH_MEMORY";
            break;
        default:
            qInfo()<<__func__<<"unknown status codes:"<<status;
        }
        if(camera_ids){
            qInfo()<<__func__<<"camera number:"<<camera_ids->numCameras;
        }
    }else{
        qInfo()<<__func__<<"cannot create camera manager";
    }
}

#endif

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

#ifdef Q_OS_ANDROID
    qInstallMessageHandler(myMessageHandler);
    open_android_camera();
#endif

    MainWindow w;
    w.show();

    return a.exec();
}

```

Error code returned by ACameraManager_getCameraIdList is -866653748, none of the value of NdkCameraError.h looks like that, weird

**Comment by ggfan** [comment]
Oops, I do not have knowledge for Qt, but passing on to Professor Camera's office to see if they could give it a glimpse; will let you know.

**Comment by ggfan** [comment]
For this one particularly, need to have the logcat output to do some more "clinics". How about this:
- create an item on StackOverflow, make sure  word "camera2" included in your question
- attach your logcat output
- link your created stackoverflow item here(to this bug, this is optional -- but nice to have )

Camera team will follow up there on StackOverflow; and I will close this one here.

**Comment by stereomatchingkiss** [comment]
> 
> 
> For this one particularly, need to have the logcat output to do some more "clinics". How about this:
> 
>     * create an item on StackOverflow, make sure  word "camera2" included in your question
> 
>     * attach your logcat output
> 
>     * link your created stackoverflow item here(to this bug, this is optional -- but nice to have )
> 
> 
> Camera team will follow up there on StackOverflow; and I will close this one here.

Thanks

- Item at [StackOverflow](https://stackoverflow.com/questions/59246410/cannot-get-camera-list-by-android-ndk#59246410)
- [logcat output](https://pastebin.com/8jmxK6bR)

**Comment by stereomatchingkiss** [comment]
> 
> 
> Oops, I do not have knowledge for Qt, but passing on to Professor Camera's office to see if they could give it a glimpse; will let you know.

Before you find out what cause the weird return value, could you show me the examples(or keywords, so I could find the examples) how to get the camera frame by the java api?I want to get the frame, pass it back to c++ side and do something with the camera frame.

Every examples I found show us how to use the existing camera app and capture the image, example of opencv need to draw the frame on preview.

**Comment by stereomatchingkiss** [comment]
Do I need to create an Activity and initialize the camera in the onResume function?

**Comment by ggfan** [comment]
https://github.com/android/camera-samples is the classic example and well maintained, may you check on that? @yaraki is the author for that one, definitely could save you from searching with keywords.

**Comment by stereomatchingkiss** [comment]
Update logcat, more information

[Link of the logcat](https://drive.google.com/open?id=1KkQEKzsviVHLAlzDFFiI_EGZGW7Jmlr5)

This logcat is generated by "adb logcat > logcat.txt", please tell me if I do it wrong or you need more info, thanks.

**Comment by ggfan** [comment]
please attach it to your StackOverflow item, Dr.'s business is on that front  :-)

**Comment by stereomatchingkiss** [comment]
> 
> 
> please attach it to your StackOverflow item, Dr.'s business is on that front :-)

Thanks, attached already.

**Comment by ggfan** [comment]
great, Camera team already engaged with your StackOverflow item. I am closing down this one ( if you could load the Camera example in this repo on the phone you are using,  you could confirm yourself that that phone supports camera2: they have something special in their vendor firmware for camera for that manufacturer ). But yeah, keeps that Stackoverflow item alive would be good (you could notify them your full adb logcat is available now  )

**Comment by stereomatchingkiss** [comment]
> 
> 
> great, Camera team already engaged with your StackOverflow item. I am closing down this one ( if you could load the Camera example in this repo on the phone you are using, you could confirm yourself that that phone supports camera2: they have something special in their vendor firmware for camera for that manufacturer ). But yeah, keeps that Stackoverflow item alive would be good (you could notify them your full adb logcat is available now )

Thanks, already told them by comments. Could you ask them they could found the logcat or not?

**Comment by ggfan** [comment]
sure thing, I will reminder the team
