### ISSUE TITLE
Custom "ANativeActivity_onCreate" function is never called (again)

### ISSUE THREAD

**Issue by Gibson85** [android/ndk-samples#683]
Hi,

since two days I am failing to get the "ANativeActivity_onCreate" function getting called.
I am not using "native_app_glue".

If I set up a simple test program with the "ANativeActivity_onCreate" function being part of my native "MyNativeActivity" lib its getting called and I see the log message:

```
extern "C" {
JNIEXPORT void ANativeActivity_onCreate(ANativeActivity* activity, void* savedState, size_t savedStateSize)
{
	LOGI("ANativeActivity_onCreate ...");
}
}
```

```
target_link_libraries(
		MyNativeActivity
		PUBLIC
        android
		${log-lib}
		#${MyLibA}
		#${MyLibB}
		#${MyLibC}
		#${MyLibD}
		#${MyLibE}
)
```

But now it becomes strange.

As soon as I add some additional shared libs MyLibA - MyLibE (see above) which get linked to the "MyNativeActivity" lib also the "ANativeActivity_onCreate" function never gets called again. At least I do not see the log message anymore. No error message is shown also.

I also tried with and without the following linker flag:
```
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -u ANativeActivity_onCreate")
```
I did hundrets of rebuilds, deleted all build files, deleted & reinstalled the application from the phone  and also tried to use a custom function name:
```
<meta-data
                    android:name="android.app.func_name"
                    android:value="NativeActivityInit" />
```
But all without success.
What can cause this behaviour?

My final goal was to move the "ANativeActivity_onCreate" function from my "MyNativeActivity" lib to one of the other shared libs and being called there. This worked some time ago, but it seems not anymore? I also checked the existence of the function symbol at the lib.

**Comment by Gibson85** [comment]
Ok, I experimented a bit and found out a few things.
If I define the "ANativeActivity_onCreate" function in one of my libs it gets called:

```
I/art: Late-enabling -Xcheck:jni
W/System: ClassLoader referenced unknown path: 
ANativeActivity_onCreate: 0x5b817f40...
...ANativeActivity_onCreate
D/libEGL: loaded /system/lib/egl/libEGL_mali.so
D/libEGL: loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL: loaded /system/lib/egl/libGLESv2_mali.so
```

If I define it on my second lib or I link against the second one not:

```
I/art: Late-enabling -Xcheck:jni
W/System: ClassLoader referenced unknown path: 
D/libEGL: loaded /system/lib/egl/libEGL_mali.so
D/libEGL: loaded /system/lib/egl/libGLESv1_CM_mali.so
```
As you can see the log message...

```
D/libEGL: loaded /system/lib/egl/libGLESv2_mali.so
```
... is also missing now.
A second maybe minor problem is the following log message I see as soon as I set the "hasCode" property of the "NativeActivity" to "false":
```
W/System: ClassLoader referenced unknown path: 
```

Also I linked my libs into your "native-activity" ndk example.
And interestingly then the OpenGL animation changing the background color is broken.
And because my problematic lib also uses OpenGL,
I am pretty sure that the problem is related to OpenGL.

**Comment by ggfan** [comment]
ANativeActivity_onCreate() is already implemented inside android_native_app_glue.c inside NDK, you could not re-implement it, otherwise the "glue" between Java side ANativeActivty and C/C++ code is broken.  android_native_app_glue.c is directly pulled into the project from your ndk's local installation.

**Comment by Gibson85** [comment]
Sure you can re-implement it. You simply shouldn't use android_native_app_glue then. It seems I have a strange linking error. I open a new issue for that.
