### ISSUE TITLE
AndroidBufferQueue Callback not triggered from OpenMAX AL 

### ISSUE THREAD

**Issue by kapil1992** [android/ndk-samples#687]
I am using ndk-sample/native-media in which i am trying to pass decrypted data to openMax buffer. But i am getting the callback for some packets then it stops and not triggered at all.

I am not getting the issue. Can you suggest like on what condition the callback is triggered and when it stops triggering as its not returning no error after enqueue data.

thanks in advance...

**Comment by ggfan** [comment]
thank you for filing the issue, will look at this and report back  ( might take some time, sorry )

**Comment by DanAlbert** [comment]
It sounds like you're talking about an OS bug? If so, http://b.android.com, and file a frameworks bug. Sorry you weren't redirected sooner.

FYI though you might also want to try switching to https://github.com/google/oboe. Doing audio stuff on Android without it is just playing the game on hard mode.
