### ISSUE TITLE
Unsupported method: NativeArtifact.getSourceFolders()

### ISSUE THREAD

**Issue by pspansong** [android/ndk-samples#690]
Unsupported method: NativeArtifact.getSourceFolders().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

Then: change/upgrade the target version of Gradle. which version?

**Comment by ggfan** [comment]
may you put more details about your environment:
 - android studio version
 - the code you are building
?

sorry about the delay :-(
