### ISSUE TITLE
Can not run display-p3 on Pixel 2 (Android 10)

### ISSUE THREAD

**Issue by wchen61** [android/ndk-samples#697]
Display-P3 can not run on Pixle2 (Android 10), I think this is because the egl extension does not have EGL_EXT_gl_colorspace_display_p3.  I have dump all the egl extensions as follow

EGL version is 1.5
EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_lock_surface EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_create_context_no_error EGL_KHR_mutable_render_buffer EGL_EXT_yuv_surface EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context 

When I use dumpsys SurfaceFlinger, and I find this display is support wide-color, and screen also is display-p3.

Wide-Color information:
Device has wide color built-in display: 0
Device uses color management: 1
DisplayColorSetting: Managed
Display 0 color modes:
    ColorMode::NATIVE (0)
    ColorMode::SRGB (7)
    ColorMode::DISPLAY_P3 (9)
    Current color mode: ColorMode::SRGB (7)

My question is why the pixel2 does not have the p3 egl extensions.

**Comment by ggfan** [comment]
yeah, P3 depends on the hardware capability. Pixel 3+ is required.

**Comment by wchen61** [comment]
thank you, @ggfan. I want to know why the extensions does not show on pixel2 (Android 10). When I run under pixel2 (Android 9), it does exist. I have a question on stackoverflow, could you please give some hint.
https://stackoverflow.com/questions/60524958/how-to-create-the-surface-with-p3-colorspace-use-egl-extension

**Comment by mirh** [comment]
How about vulkan? Does it have `VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT` or `VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT` ?
