### ISSUE TITLE
unavailable NDK version 21.1

### ISSUE THREAD

**Issue by ricardoquesada** [android/ndk-samples#702]
ndk-samples requires NDK version 21.1.6210238.
However that version is unavailable to download, at least from Android Studio.
The available NDK versions are shown in the attached screenshot:
![ndk-versions](https://user-images.githubusercontent.com/232330/78063242-c0edc600-7344-11ea-97c9-41169a48ed9d.png)

But the main problem with ndk-samples and the rest of the Android samples is that the required specific NDK and SDK-TOOLS versions.
Instead of requiring NDK-version `21.1.6210238` it should require NDK version `21.*` or similar.

**Comment by ricardoquesada** [comment]
update:
I tried downloading the NDK from the official site (  https://developer.android.com/ndk/downloads ), and the latest one is still 21.0, not 21.1.

two suggestions:
- before bumping the NDK version, make sure it is available for download.
- don't force uses to use beta version. create two branches. devel and master (or whatever name you prefer).

**Comment by ggfan** [comment]
Android Studio menu, "settings > Appearance & Behavior > system Settings > Updates"
   choose "Canary Channel"
The canary NDKs will be enabled for download:
  "Tools > Sdk Manager > SDK Tools"
    ( assuming "Show Package Details" is enabled )
  "NDK side by side"

you second question about specific version to support wildcard, not possible now; will report to plugin / studio team about it.

Dev branch works, might affect the discoverability and link to the doc; yeah the idea is valid one, thought about the methodology before, maybe it should be adopted, keeping it open for now.

**Comment by ricardoquesada** [comment]
Thanks for the quick reply! that fixed.

So, another suggestion:
When using Android Studio stable channel I'm able to download:

- SDK Platform: Android R Preview
- Android SDK Build-Tools RC1 and RC2

But I cannot download the NDK 21.1 RC versions.

So, my suggestion is that it should be consistent: either none of the Preview/RC/Beta should be available, or all of them should be available.
I'd prefer that all of the should be available, because I want to use Android Studio stable (I want an stable editor), but sometimes I want to test unstable APIs.

And I've just realized that I need to install Android R on my phone.
```
Skipping device 'Pixel 4 - 10' for 'image-decoder:debug': minSdkVersion [R] > deviceApiLevel [29]
```
And that's something that I prefer not to do now. So, having "stable" branch would be great.

Thanks!

**Comment by ggfan** [comment]
image-decoder is for Android R and above, that is the reason to be in minSdkVersion.    
other samples (classic-teapot  for example) should be ok.

Answer to your other request: "Consistency is still a dream", I would not start request at all now :-).  But I could see you are my friend, and keeps the dreaming on. :-)

**Comment by fatalfeel** [comment]
Android studio Eclipse debug jni on ndk 20b 19c test ok
http://fatalfeel.blogspot.com/2013/10/android-studio-with-eclipse-debug-jni.html

**Comment by ggfan** [comment]
could you help to follow the instruction here (wiki of this repo ) to install the canary version:
  https://github.com/android/ndk-samples/wiki/Configure-NDK-Path#install-ndks ?

The working command should be something like:
```
.../sdk/tools/bin/sdkmanager --channel=3 --install "ndk;21.1.6273396"
```
please help to review the whole doc if possible, and let me know how do you feel and report bugs about the doc here too: I will insert screenshot into the doc someday this or next week.   Thank you and I will close this issue for now.

**Comment by ricardoquesada** [comment]
will do that. thanks.
