### ISSUE TITLE
Problem using std::__ndk1::__fs::filesystem

### ISSUE THREAD

**Issue by rpsfonseca** [android/ndk-samples#703]
I am trying to use std::__ndk1::__fs::filesystem on a NDK app.

I have added the necessary configurations to the CMake file, but I get this error when compiling:
`error: undefined reference to 'error: undefined reference to 'std::__ndk1::__fs::filesystem::directory_iterator::__increment(std::__ndk1::error_code*)'`

Is there anything else necessary to add?

**Comment by ggfan** [comment]
the master says: not available yet. Those compiler things would be good to ask at [ndk public page](https://github.com/android/ndk):  https://github.com/android/ndk/issues/609.  Sorry from me for now.
