### ISSUE TITLE
Unable to set breakpoint into C code 

### ISSUE THREAD

**Issue by windmaple** [android/ndk-samples#705]
Fresh clone of this repo. Android Studio 3.6.2. I opened hello-jni.c and set a breakpoint at 

return (*env)->NewStringUTF(env, "Hello from JNI !  Compiled with ABI " ABI ".");

Then click 'debug'. The breakpoint is ignored. Have tried the solution in https://github.com/android/ndk/issues/197, but it didn't help. 

What do I need to do to enable debugging in native code?

**Comment by ggfan** [comment]
3.6.2 should just work as-is, assume the project is already imported to Android Studio IDE:
  - "Build Variants" low left edge, click on it
  - you should see the arm8Debug is selected ( for arm64-v8a )ABI
  - create a breakpoint on the line you mentioned
  - menu "Run" > "Debug app"
My pixel 3a with Android R Developer Preview would stop at the breakpoint.

more details about your:
  - host system: windows, mac?
  - Android device and OS version?  ( if emulator, emulator version and your device spec ).

it should work, got to be something else.
