### ISSUE TITLE
wiki: NDK configuration minor fixes.

### ISSUE THREAD

**Issue by ricardoquesada** [android/ndk-samples#709]
First of all, thanks for updating the https://github.com/android/ndk-samples/wiki/Configure-NDK-Path

Some feedback:

**A)**

On the one hand, I found the documentation very valuable. Learned many things. I think the info contained here is so valuable that it should be "promoted" to a place with your visibility... perhaps to the official NDK page (?). 

On the other hand, I found it somewhat confusing. For example, the documentation talks about AGP, and depending on what version of you have, you might need to do something. But it is not clear how I got AGP installed in the first place and how to check the version. I assume that AGP is associated with Android Studio and they share the same version. If so, that should be mentioned on the wiki.

Also, I found the `sdkmanager` binary wasn't working for me.
I found that I have two binaries in the $ANDROID_SDK path:

- $ANDROID_SDK/tools/bin/sdkmanager: doesn't work for me... crashes with some Java error
- $ANDROID_SDK/cmdline-tools/latest/bin/sdkmanager: works Ok for me.

It is not clear for me why I have two installed. I guess because I switched from stable to canary? Not sure. I found that the official sdkmanager page also refers to the one in "tools/bin".

**B)**

I attached a patch that includes minor fixes (I don't know how to send a pull request to a wiki page).

[0001-ndk-samples-wiki-minor-improvements.patch.zip](https://github.com/android/ndk-samples/files/4487575/0001-ndk-samples-wiki-minor-improvements.patch.zip)

**C)**

But one possible way to "promote" this page is to move it from the wiki-project, to the main ndk-samples project.
That way, when you clone the repo, you also get the documentation with you.

Additionally, if you do this, you can easily process the markdown file with `go/mdformat` (or the tool that you prefer, and that will catch some minor issues).

**Comment by ggfan** [comment]
thank you! yeah, AGP(Android Gradle Plugin) is the backend of the Android Studio( except UI ), will add it into the doc.  The version of it would in the DSL of [project build.gradle](https://github.com/android/ndk-samples/blob/master/nn-samples/build.gradle#L9) like:
```
   classpath 'com.android.tools.build:gradle:4.1.0-alpha02'
```
on command line build, it is all about AGP/Gradle.

for sdkmanager, which host OS you are on:  Windows?  also see what version it is:
```
   tools/bin/sdkmanager --version
```
(mine is 26.1.1)

Let me take care of "B & C" and update here later

thank you again for review!

**Comment by ricardoquesada** [comment]
I'm on Linux, Ubuntu 20.04
```
cd $ANDROID_SDK
$ ./cmdline-tools/latest/bin/sdkmanager --version
3.6.0
```

And the "old" one:
```
$ cd $ANDROID_SDK
$ ./tools/bin/sdkmanager --version
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

**Comment by ggfan** [comment]
inside the Android Studio, could you go to SDK manager to update "SDK Tools"
   Android SDK Tools
   Android SDK Platform-tools

make sure your Android Studio using the SDK you pointed too ( normally it is decided by your ANDROID_SDK_HOME)

then see if it  could get you going? thx

**Comment by ggfan** [comment]
yeah you are right: the tools are installed, now, to this new location you mentioned. I will update the wiki doc to reflect it.  thanks for pointing it out!

**Comment by ggfan** [comment]
To assist the collaboration, put the docs into [documentation](https://github.com/android/ndk-samples/tree/documentation) branch;I believe your patch is added into [the wiki page](https://github.com/android/ndk-samples.wiki.git) already.

I am reluctant to put the doc into the sample code: the eventual doc could be on developer.android.com or/and this wiki page.  Next doc is the Android CMake options for the wiki, hopefully to save people some time.
