### ISSUE TITLE
in nnapi example, Devices except CPU does not work with Conv_2D, MUL, ADD, etc.

### ISSUE THREAD

**Issue by yskimno1** [android/ndk-samples#726]
when I use ANeuralNetworksCompilation_createForDevices, my devices, like edgeTPU, qci-gpu, ... they do not support conv_2d, mul, add operations now.
It shows that "E/ExecutionPlan: No driver can do the op".

Also, when I check operations with ANeuralNetworksModel_getSupportedOperationsforDevices, all of devices returns false with above operations, except "nnapi-reference", which means CPU.

How can I solve this problem?

**Comment by miaowang14** [comment]
The compilation / execution is expected to fail if the selected device is not supporting the entire model.

Many devices have requirements on the parameters of an operation in order to support it.
For example, for CONV_2D, many devices require the filter tensor to be constant. (You can refer to https://developer.android.com/ndk/guides/neuralnetworks#model to set the constant data.)

Also, many devices only supports specific data types, e.g. edgetpu currently only supports uint8 tensors.

**Comment by yskimno1** [comment]
Thank you for the answer! I'm now wondering that GPU did not support MUL, ADD operations(elementwise) between float32 tensors. Is it similar to the reason with constant issue?

**Comment by yskimno1** [comment]
> The compilation / execution is expected to fail if the selected device is not supporting the entire model.
> 
> Many devices have requirements on the parameters of an operation in order to support it.
> For example, for CONV_2D, many devices require the filter tensor to be constant. (You can refer to https://developer.android.com/ndk/guides/neuralnetworks#model to set the constant data.)
> 
> Also, many devices only supports specific data types, e.g. edgetpu currently only supports uint8 tensors.

d

**Comment by miaowang14** [comment]
TBH, I am not sure about the parameter space that is supported by the GPU interface, as it differs for different devices and Android versions.

Could you post code related to the ADD / MUL op here? And what is the device and Android version of your device?

**Comment by yskimno1** [comment]
I think it works well now. I have set most of values with inputs, which are determined at computation stage. Thank you for the kind answers!

**Comment by tupv495** [comment]
Hi @yskimno1, 
 I am facing the exact same issue as yours here. could you please explain how you overcome this issue?
Thank you very much!

**Comment by yskimno1** [comment]
@tupv495 At the first question, some devices, like edgeTPU, did not support some operations, so I've changed the operations.

Also, you may delete ANeuralNetwork_setOperandValue functions to calculate operations. I cannot see my code now, but it would work!
