### ISSUE TITLE
Feature request:  A sample show how to  built with the NDK under Address Sanitizer. 

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [android/ndk-samples#737]
As the title, I'm not clear how to use Address Sanitizer in Android studio with native code, Hope give a sample show how to use it. thanks!

**Comment by ggfan** [comment]
In this subject, there probably 3 options:
  - Generic Asan : https://developer.android.com/ndk/guides/asan#cmake
  - HWAsan( need special OS build ): https://developer.android.com/ndk/guides/hwasan
  - GWP-ASan (Android 11+): https://developer.android.com/ndk/guides/gwp-asan

There are not programming feature/new APIs, just tools.  Tools are better described with docs or codelabs. Which doc you are referring too?

Sometimes, the docs on developer.android.com/ndk assumes people already have rich domain knowledge about that specific topic: might need to be expanded to provide the whole picture.

**Comment by DanAlbert** [comment]
https://github.com/android/ndk-samples/tree/main/sanitizers
