### ISSUE TITLE
audio-echo demo does not work on Samsung Galaxy S20 Ultra 5G

### ISSUE THREAD

**Issue by chrbsg** [android/ndk-samples#738]
audio-echo does not work on a Samsung Galaxy S20 Ultra 5G. After pressing "Start Echo" there is a short burst of audible noise/static, but no echo audio, and logcat shows:

    2020-06-08 15:03:20.156 10429-10548/com.google.sample.echo D/AudioTrack: stop(94): called with 15744 frames delivered

It always shows stop at 15744 frames, despite the UI still showing the stop button. The demo works ok on two other phones I have for test (Pixel 2 XL and Wileyfox Swift 2), so I would guess this is a specific issue with some phones rather than a build problem.

**Comment by ggfan** [comment]
This could be device dependent, thank you for reporting the issue. 
Android 11 and above recommends  [Oboe](https://github.com/google/oboe), there are a group of samples in that repo;  OpenSL/ES is being deprecated, unlikely there will be more development with this sample; may you use oboe for your new development?

**Comment by dturner** [comment]
Related issue: https://github.com/google/oboe/issues/892

**Comment by philburk** [comment]
Closing as a DUP of https://github.com/google/oboe/issues/892
