### ISSUE TITLE
Couldn't get camera to capture any image using the NDK camera API in commandline

### ISSUE THREAD

**Issue by tianli** [android/ndk-samples#743]
Well, first of all, the original NDK samples for camera works fine in an App setting. What I am struggling with is to get the same code to capture the images from camera when launched in commandline (e.g. from termux or adb shell). The permissions are granted using termux:API's termux-camera-photo command (https://wiki.termux.com/wiki/Termux-camera-photo), which calls the java app.

I have stripped down the ndk sample code to just enough to launch the camera, and put it on github https://github.com/mu-opensource/ndk-cameras-cmdline. Again, this is not a permission issue, the camera can open and session started in the commandline binary, just cannot receive any image from the camera service.

From the comparison of logcat with the ndk-sample app, I can see one critical step is missing:
After the session started, the logcat shows it is missing this line:
---- From logcat of the ndk-samples camera app ----
08-14 08:02:18.166  3837  3860 D CamX    : [DEBUG][CORE   ] camxsession.cpp:2369 ProcessRequest() pipeline[0] OpenRequest called for request id = 13
---- End of logcat ----

---- From logcat of the ndk-camera binary ---
08-14 08:04:00.086   936   936 E Camera3-Device: configureStreams: Stream 0: DataSpace override not allowed for format 0x23
08-14 08:04:00.086   936   936 E Camera3-Device: configureStreams: Stream 1: DataSpace override not allowed for format 0x21
08-14 08:04:00.088 10166 10168 W NDK-CAMERA: session 0x79970a2b40 is active
!!! no ProcessRequest() ever !!!
---- End of logcat ----

Any suggestions? Do I need to open a real surface in order to receive captured image or the camera service will silently ignore any request?

**Comment by tianli** [comment]
BTW, I also wondering why it will take almost 500 lines of code just to start streaming images from the NDK camera!

**Comment by ggfan** [comment]
thank you for filing the issue! I need to catch up with camera API update after original camera 2; the original operation was a callback from camera when an image is ready, then inside the callback app needs to copy the image out -- you got the image there.  As for complexity question, we could probably discuss it later after solving the real issue.

**Comment by tianli** [comment]
Thank you for the comment. Yes I do remember that in java you get the image using a preview call back. But I could not find it in the NDK in c++. The camera sample here just loop around to draw frames from the AImageReader.

And I made some progress now, I found out that the ANativeWindow I got from the ImageReader::GetNativeWindow() is not good. The camera API does not like it (probably because it does not associated with a real Surface). If I create a real surface using SurfaceComposerClient, and pass it in the NDKCamera::CreateSession, the camera API will run and I can see real request being processed. I will update my github repository later to reflect what I found out.

**Comment by ggfan** [comment]
Glad you have made some progress.  The other difference is ImageListener:
```
  AImageReader_setImageListener(reader_, &listener);
```
probably should use the callback to read out the images: when image is ready, you get notified, then you read it out there with AImageReader_acquireNextImage(), and finally return control back to AImageReader.  In other words, you got the image inside the AImageReader's callback thread.  you could also try AImageReader_acquireNextImageAsync() added in API level 26 to avoid pulling.

**Comment by ggfan** [comment]
@tianli just ping,  could you capture a bugreport with your app?

**Comment by tianli** [comment]
Hi, Yes, I captured a bug report a couple of weeks ago. You can download it from my google drive [https://drive.google.com/file/d/1zfpJP_5kHDlemsV0_fBBF9JX6J0sMedQ/view?usp=sharing](url)

**Comment by tianli** [comment]
I took a look at some other samples, and they all seem to have a real surface (window) as the target of the camera data. Does that mean the native window I got from AImageReader_getWindow() alone is not enough to trigger the sensor to stream the image data?

Tianli.

**Comment by tianli** [comment]
I also checked the logcat output, out of the tons of output, this one seems to be most relevant, some complaining about invalid handle. This happens if I use the nativeWindow from ImageReader, but not with real surfaces created using SurfaceComposerClient().

09-16 17:26:01.297   687  1370 E CamX    : [ERROR][SENSOR ] camxpdafdata.cpp:330 PDAFInit() PDAF Error: Invalid Handle, Failed to initialize PD Library
09-16 17:26:01.300 17612 17616 W NDK-CAMERA: session 0x7d890a2fa0 is active

**Comment by ggfan** [comment]
ok, will take a look at it soon and update you here, thank you!

**Comment by tianli** [comment]
Thanks, Gerry. I looked up PDAF and it seems to be auto focus related error, which might not be the real issue. Anyway, I am trying to get the RAW format and there seems no other way than using the ImageReader approach. The format I got using a real surface as ANativeWindow is of YUV format.

**Comment by EasonZxp** [comment]
Hi tianli:

Do you have got the preview frames through ImageReader surface? Wait for you updating your github repository ...

**Comment by EasonZxp** [comment]
@tianli Now i also meet the issue that onImageAvailable not called back. Do you have solved this issue? wait for your replay~

Thanks.

**Comment by tianli** [comment]
@EasonZxp no, I couldn't ImageReader to work. What works for me is passing a real surface. Let me update my github to reflect the change.

**Comment by EasonZxp** [comment]
@tianli OK. It is a rather odd question. I tested ImageReader worked with android SDK functions.  Don't know why it's not worked with NDK functions.  Can you update your github that how to  pass a real surface there?

**Comment by tianli** [comment]
@EasonZxp I updated the repo to add the code that I tested that works in NDK. Check this function call where a surface is created internally to receive the preview.

https://github.com/mu-opensource/ndk-cameras-cmdline/blob/aec3f711706329f3edad26b9c64edbcb522c218a/src/main.cc#L13

https://github.com/mu-opensource/ndk-cameras-cmdline/blob/aec3f711706329f3edad26b9c64edbcb522c218a/src/ndk/ndk-camera.cc#L202

**Comment by dhatri14** [comment]
Any further progress on getting images?

**Comment by tzjb** [comment]
Any updates on this issue? I ran into similar issue here. I have a C++ wrapper class that opens camera and captures images. If this C++ class is called from an APK (in Java), everthing works fine, images are captured as expected. But the same C++ class called from a native C++ program (not an APK, but a Linux executable) on the same Android device, no images are available even though the Camera2 API says camera is opened without errors.

**Comment by DanAlbert** [comment]
afaik there's no expectation that the framework APIs are usable outside an app. If that's something you need, you need to file an OS bug against the framework: http://b.android.com.
