### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by sonicdjgh** [android/ndk-samples#744]
[](url)
![screen](https://user-images.githubusercontent.com/29569541/90956279-a49b2300-e4b7-11ea-92fe-089bf27351ea.png)

I got a issue like this...

**Comment by ggfan** [comment]
Thank you for filing the issue,  a couple of questions:
1. how do you compile the project: full steps please from git clone, to the step you saw the reported issues
1. try it on a non Huawei phone, confirm that it still happens and update the bug with that phone details?
thank you

**Comment by kim-ninh** [comment]
I had the same problem. I solved it by delete 2 folders ".cxx", "build" in "hello-libs/app" and rebuild project.

Step to reproduce: 

- Uncomment *include ':gen-libs'* in settings.gradle
- Uncomment *api project(':gen-libs')* in build.gradle  (app module)
- Build -> Build APK
- Comment *include ':gen-libs'* in settings.gradle
- Comment *api project(':gen-libs')* in build.gradle  (app module)
- Rebuild project

**Comment by ggfan** [comment]
Thank you for the detailed report and root causing!  Building lib is just to show a way of generating libs, it is *not* common to use the external lib and also build it from source in the same project; but this should be documented to avoid future confusion, added [PR# 766](https://github.com/android/ndk-samples/pull/766) to fix it.
