### ISSUE TITLE
OpenSL ES log

### ISSUE THREAD

**Issue by wanliyang1990** [android/ndk-samples#750]
Hello, I used opensl es to play sound，how to close the log "D/AudioTrack: stop(90296): called with 1024 frames delivered"， thanks.

**Comment by gkasten** [comment]
This message comes from
https://cs.android.com/android/platform/superproject/+/master:frameworks/av/media/libaudioclient/AudioTrack.cpp?q=%22frames%20delivered%22
It does not seem to be very important. Are you experiencing any problems?

**Comment by wanliyang1990** [comment]
I want to close this log, it prints too often.

**Comment by ggfan** [comment]
If you are using andrioid studio, you could control the logcat message level ( warning, error ...) pretty easily; on command line / terminal, will need to use regexp  or tag:priority option like ```adb logcat AudioTrack:E```, piping also useful.  The idea is to "pick up the related info". There are certainly lot of logcat messages out there from different modules in Android OS, your feedback is well heard. Thank you again!

**Comment by wanliyang1990** [comment]
OK，thanks！
