### ISSUE TITLE
.so and .a libs

### ISSUE THREAD

**Issue by sarashawky** [android/ndk-samples#754]
I need to use .so and .a libraries and the below exeption is appeared 
![Capture](https://user-images.githubusercontent.com/15781563/96441972-ac9ee700-120a-11eb-9538-e2d6dfc7c495.PNG)

**Comment by ggfan** [comment]
libcabarcode.so probably is your own library, if want to add it into your project ( native-lib ), you could have a look at the [hello-lib sample](https://github.com/android/ndk-samples/tree/main/hello-libs). Otherwise, we might need more context to follow up with the issue you are experiencing.

**Comment by sarashawky** [comment]
Thanks a lot for your help.
the libcabarcode.so is not built with android and I didn't have its source code, as in hello-lib sample the libraries is generated with android, Is there any way to use a prebuilt library not generated on android before?

**Comment by ggfan** [comment]
The hello-libs sample is meant to use externally build libraries ( someone else's library for Android ) and use it in your application.  Follow the app module: the library module by default is not built in the project. It is kind of CMake's thing, check out [app's CMakelist.txt](https://github.com/android/ndk-samples/blob/main/hello-libs/app/src/main/cpp/CMakeLists.txt#L29) for usage.

**Comment by sarashawky** [comment]
I follow the hello-libs sample and I add libcabarcode.so to the  distribution_DIR and the below error is appeared
![Image20201020214445](https://user-images.githubusercontent.com/15781563/96636456-9b92ca80-131d-11eb-92c7-836f3c5aa2cc.png)
CMakelist.txt is below 
[CMakeLists.txt](https://github.com/android/ndk-samples/files/5410840/CMakeLists.txt)

library
[libcabarcode.zip](https://github.com/android/ndk-samples/files/5411193/libcabarcode.zip)

**Comment by ggfan** [comment]
Oh, look at the [library structure under distribution](https://github.com/android/ndk-samples/tree/main/hello-libs/distribution/gperf/lib), you would need 4 flavor of the same lib: `arm64-v8a, armeabi-v7a, x86, x86_64`. Your lib is for armeabi-v7a ( 32 bit ), so you could only compile for 32 bit arm application with: ` android.ndk.abiFilters='armeabi-v7a'`, it works.

If you need to compile for all 4 platforms, get the 4 libcabarcode.so files, then look at how the sample configure it, you would be able to compile.

**Comment by sarashawky** [comment]
Many thanks for your Help

I have recieved another error after compile with 
`android.ndk.abiFilters='armeabi-v7a'` 

errorLogs
`Build command failed.
Error while executing process C:\Users\sshawky\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C D:\Users\sshawky\Downloads\ndk-samples-master\hello-libs\app\.cxx\cmake\debug\armeabi-v7a hello-libs}
ninja: Entering directory `D:\Users\sshawky\Downloads\ndk-samples-master\hello-libs\app\.cxx\cmake\debug\armeabi-v7a'
[1/2] Building CXX object CMakeFiles/hello-libs.dir/hello-libs.cpp.o
[2/2] Linking CXX shared library D:\Users\sshawky\Downloads\ndk-samples-master\hello-libs\app\build\intermediates\cmake\debug\obj\armeabi-v7a\libhello-libs.so
FAILED: D:/Users/sshawky/Downloads/ndk-samples-master/hello-libs/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libhello-libs.so 
cmd.exe /C "cd . && C:\Users\sshawky\AppData\Local\Android\Sdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi16 --gcc-toolchain=C:/Users/sshawky/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/sshawky/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -std=gnu++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libhello-libs.so -o D:\Users\sshawky\Downloads\ndk-samples-master\hello-libs\app\build\intermediates\cmake\debug\obj\armeabi-v7a\libhello-libs.so @CMakeFiles/hello-libs.rsp  && cd ."
C:/Users/sshawky/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: warning: shared library text segment is not shareable
C:/Users/sshawky/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: treating warnings as errors
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.`

**Comment by ggfan** [comment]
may you add this `set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--no-warn-shared-textrel")` to you CMakeLists.txt?  you might want to contact library owner to see if libcabarcode.so is built with `-fPIC`?
somehow OS X does not bother it though.

**Comment by sarashawky** [comment]
After adding `CMAKE_SHARED_LINKER_FLAGS` the build done successfully 
but when the app is crashed with the below exception

`$ adb shell am start -n "com.example.hellolibs/com.example.hellolibs.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 9071 on device 'unknown-saturn1000-0123456789ABCDEF'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
E/linker: /data/app/com.example.hellolibs-1/lib/arm/libhello-libs.so: has text relocations
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.hellolibs, PID: 9071
    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.example.hellolibs-1/lib/arm/libhello-libs.so: has text relocations
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.example.hellolibs.MainActivity.<clinit>(MainActivity.java:36)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.access$900(ActivityThread.java:150)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`


Maybe that occur as library built with `-fPIC`?
I will contact the owner to make sure also.
Thanks alot again

**Comment by ggfan** [comment]
yeah contact the lib owner would help: they would have instructions on how to use the lib.

**Comment by sarashawky** [comment]
Ok, Thanks alot for your support
