### ISSUE TITLE
Building app Native-activity with ndk

### ISSUE THREAD

**Issue by DanGdl** [android/ndk-samples#765]
Hello
I'm trying to build app Native-activity with ndk and receive such error:
Error:Module 'native-activity' production: java.lang.NoClassDefFoundError: com/android/resources/ResourceFolderType

What can lead to such error?
Thanks

**Comment by ggfan** [comment]
you get the fresh code out of the repo and get that error?  on windows? where is your NDK location installed on your development system?

**Comment by DanGdl** [comment]
fresh code from repo
System Manjaro
ndk path: /usr/share/androidSdk/ndk/21.3.6528147/

**Comment by ggfan** [comment]
you could build other samples without problem on that OS? tested OSes are at the bottom of[ studio website](https://developer.android.com/studio), that linux is not tested, but not sure that is the issue though.

**Comment by DanGdl** [comment]
I didn't try. Samples with cmake are built ok. Possible I'm doing something wrong
Thank you for help

**Comment by ggfan** [comment]
if you could build other cmake samples, only the native-activity one, it is alarming. wondering if you could do a build inside terminal with:
   ./gradlew clean build
for native-activity and teapot samples ( probably also hello-jni ), and see what you get.

**Comment by ggfan** [comment]
kind of confirmed that your OS is not within the OSes studio/android gradle plugin was validated. Again I am not totally sure that is the problem.

**Comment by DanGdl** [comment]
OS:
OS: Manjaro 20.2 Nibia
Kernel: x86_64 Linux 5.8.18-1-MANJARO
Uptime: 1d 22h 49m
DE: KDE 5.75.0 / Plasma 5.20.2
WM: KWin
GTK Theme: Breeze [GTK2],  [GTK3]
CPU: Intel Core i7-6700HQ @ 8x 3.5GHz [49.0°C]
GPU: GeForce GTX 950M
RAM: 10016MiB / 15741MiB

Android studio: ver 4.1.1, Build AI-201.8743.12.41.6953283

Teapot and native-activity from cmake are working fine.

I migradet ndk project to gradle and it is built, but app crashes (lib file is not in apk): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.native_activity/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to find native library native-activity using classloader: dalvik.system.PathClassLoader[DexPathList[[],nativeLibraryDirectories=[/data/app/com.example.native_activity-mbUSzGzSuRsVCQh57ebhLw==/lib/arm64, /system/lib64]]]


apk from cmake:
![image](https://user-images.githubusercontent.com/22168218/99699592-cc8c2980-2a9a-11eb-8ce0-9691464553d2.png)

apk from ndk:
![image](https://user-images.githubusercontent.com/22168218/99699786-09f0b700-2a9b-11eb-9d90-4325649314a3.png)

**Comment by ggfan** [comment]
"I migradet ndk project to gradle and it is built", may you elaborate more on how do you migrate ndk project to gradle: if you download as is, the project is already gradle? Thank you

**Comment by DanGdl** [comment]
My mistake. I tried to build native-activity from branch android-mk
native-activity from branch master-ndkbuild works fine

**Comment by ggfan** [comment]
Ok. the subdirectory of the main branch:  https://github.com/android/ndk-samples/tree/main/other-builds/ndkbuild also have the gradle+ndkbuild.
