### ISSUE TITLE
ld: error: found local symbol '_end' in global part of symbol table in file ../../../../src/main/jniLibs/arm64-v8a/libMNN_CL.so

### ISSUE THREAD

**Issue by saikirantokala** [android/ndk-samples#769]
Can you please help me to solve this error?

**Comment by ggfan** [comment]
How does this happen: if you just use this lib without add any code using it, would it still happen? if it is a public library, you could share the header file(s) and the so file?

**Comment by DanAlbert** [comment]
https://stackoverflow.com/a/48291044/632035
