### ISSUE TITLE
But: can't import the "webp" sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/ndk-samples#778]
I tried and it says this:

```
CMake '3.6.0' was not found in PATH or by cmake.dir property.
- CMake '3.18.1' found in SDK did not match requested version '3.6.0'.
- 
```

![image](https://user-images.githubusercontent.com/5357526/108479663-aa26c980-729e-11eb-9b7e-6bcb628140a1.png)

That's even though I've installed everything possible of CMake:

![image](https://user-images.githubusercontent.com/5357526/108479624-a135f800-729e-11eb-92e3-81ad343f8d35.png)

**Comment by ggfan** [comment]
just for a test, could install 3.6.4111459 (it is 3.6.0), see if you could do a build? If not, please put the studio version here.

Will fix in the repo to use 3.10.2 (corresponding to 3.10.2.4988404, the number at the tail of the version is build number, we do not care)

**Comment by AndroidDeveloperLB** [comment]
@ggfan I've shown you that I've installed all that the IDE allowed me.

**Comment by ggfan** [comment]
thanks! which studio version you are using?

**Comment by AndroidDeveloperLB** [comment]
@ggfan I now have this:

Android Studio Arctic Fox | 2020.3.1 Canary 7
Build #AI-203.7148.57.2031.7136282, built on February 10, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.settings.move.mouse.on.default.button=true, debugger.watches.in.variables=false
Non-Bundled Plugins: String Manipulation, com.google.mad-scorecard, org.intellij.plugins.markdown

But I had something before it.

Now the issue has changed. Now I get this one:

> Unable to find method ''com.amazon.ion.system.IonBinaryWriterBuilder com.amazon.ion.system.IonBinaryWriterBuilder.withLocalSymbolTableAppendEnabled()''
> 'com.amazon.ion.system.IonBinaryWriterBuilder com.amazon.ion.system.IonBinaryWriterBuilder.withLocalSymbolTableAppendEnabled()'
> 
> Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> 
> Re-download dependencies and sync project (requires network)
> The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> 
> Stop Gradle build processes (requires restart)
> Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
> 
> In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
> 
> 

![image](https://user-images.githubusercontent.com/5357526/108607339-721ba580-73c8-11eb-9b20-9d2be0e9eabe.png)

Sadly though, I think I get it with other projects too. 
Do you know perhaps why this occurs, and how to fix it?

**Comment by ggfan** [comment]
thanks: you are using canary 7.  you might be experiencing some real issues, I would do:
  - exit the arctic fox;
  - clean up the repo with "git clean -xdf" 
  - re-start arctic fox again;
  - click "Open" (do not use "import" which is hidden inside the extended menu)
  - browse to webp/build.gradle, and "open" it [to me it is good idea to open the top-level build.gradle when opening a project].
  
see what you will get. 

Mine went through ok.

**Comment by AndroidDeveloperLB** [comment]
@ggfan But this issue exists now everywhere when using canary.
Anyway, I now tried on beta. 
Seems to work fine there. 
What exactly does it do?
I reached it from the Android 12 web pages..

**Comment by ggfan** [comment]
Sorry for seeing this happens to you: I could not guess what could be the issue, but it seems that arctic fox is a big change. 
If you could, might be good to file a bug for Canary with detailed information. [or unofficially, remove artic fox totally from your windows, reinstall it, do not import previous studio configurations when restarting it, then go from there]

Btw, why are you looking at webp sample?

**Comment by AndroidDeveloperLB** [comment]
Because it had a link to here:
https://developer.android.com/about/versions/12/features#image-decoder

**Comment by ggfan** [comment]
yeah, the link points to the "develop" branch, not the "main" branch.  do this:
  - clone the repo
  - checkout out the "develop" branch: git checkout -b develop origin/develop"
then you will see it.

**Comment by AndroidDeveloperLB** [comment]
@ggfan That's not what the link says. It just says to go to the sample and all will be clear...

> For more details on the API, refer to the API reference and the sample on GitHub.

Guys when you publish something, make sure it's ready and easy to try it out and that it shows something that indeed demonstrates what you write about.
Why should I check other branches? The main one should be the one...

**Comment by ggfan** [comment]
thank you for your input. The samples that needs canary, or beta tools are in develop branch;  samples will be merged back to the main branch only after APIs and tools are finalized, means golden release.

The decision for developer convenience: last year community does not like the beta samples on main, so develop branch was created for that. It is kind of open source tradition from other branches, so kind of okay to serve more developers.

the branch name is in side the link, it is not hard to realized that.

**Comment by ggfan** [comment]
In the future for those questions, probably use https://www.reddit.com/r/AndroidCPP to start a discussion. I will try to use that place when there is something new coming out related to Samples and new native platform APIs.
