### ISSUE TITLE
Google Play Games C++ SDK 3.1.0 not compatible with com.google.android.gms:play-services-games:21.0.0

### ISSUE THREAD

**Issue by SysReset** [android/ndk-samples#779]
The latest Google Play Games C++ SDK 3.1.0 is not compatible with the latest com.google.android.gms:play-services-games:21.0.0 as the SDK still contains references to the removed multiplayer API functions.

**Comment by ggfan** [comment]
thank you for filing the issue: I will follow-up internally and see what we could do and update you.

**Comment by SysReset** [comment]
Are there any updates to this issue?  Google Play Games C++ SDK still crashes on startup.

**Comment by DanAlbert** [comment]
Not a samples problem. Sorry, but you should have been redirected to the people that actually have the power to fix this: https://developers.google.com/games/services/support
