### ISSUE TITLE
Not able to capture jpeg with cpp code

### ISSUE THREAD

**Issue by dhatri14** [android/ndk-samples#789]
Hi,

I have tried to remove the JNI layer, but not able to capture the .jpeg image.
AImage* image giving null data.

Platform specification.

- Android version 7
- API 24

Anyone have tried this?

**Comment by ggfan** [comment]
will try to followup this one when I get change to this(may take a while).

**Comment by DanAlbert** [comment]
I'm not sure what you're asking me to do. What sample are you talking about?
