### ISSUE TITLE
What is the minumum minSdkVersion ndk-camera support ? 

### ISSUE THREAD

**Issue by wwdok** [android/ndk-samples#790]
Is it 24 ?

**Comment by ggfan** [comment]
that is correct.  along the way there was additions to the APIs, you would find them decorated with MACRO such as:
  __INTRODUCED_IN(24)

I do not think we have documentation that lists which API is introduced with which OS version, could be a good topic, depends on the team's bandwidth(which is always tough).

**Comment by wwdok** [comment]
Ok, it is unfortunate that ndk-camera does not support Android 21, but thank you all the same with providing extra info !
