### ISSUE TITLE
[camera] texture-view crash

### ISSUE THREAD

**Issue by ShiverZm** [android/ndk-samples#793]
[enviroment] 
android studio 4.1.2
gradle plugin 4.0.0
gradle 6.1.1
api 29
ndk 21.2.6472646
[tips]
basic was running well,
but texture-view was crashed.
[log]
[debug.txt](https://github.com/android/ndk-samples/files/6368850/debug.txt)

**Comment by ggfan** [comment]
tried on Pixel + Android 10 ( API level 29 ), it starts successfully. What device you were using?
