### ISSUE TITLE
phone under the Android 10 ,can not run native-midi

### ISSUE THREAD

**Issue by listenwinding** [android/ndk-samples#798]
when i use the native-midi demo at android 9 or android 8,it have as follows error message:

java.lang.UnsatisfiedLinkError: dlopen failed: library "libamidi.so" not found

what should i do ?

**Comment by ggfan** [comment]
NDK's MIDI API was only available from Android 10+ ( Android API Level 29 ). If you run from Android Studio, the minSdkLevel should prevent starting the sample on Android 9 or 8.
