### ISSUE TITLE
[camera] deprecated jcenter() entries from top level build gradle project file

### ISSUE THREAD

**Issue by markthompson** [android/ndk-samples#801]
"Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories."

**Comment by ggfan** [comment]
this should be fixed now with https://github.com/android/ndk-samples/pull/800 & https://github.com/android/ndk-samples/pull/801 & https://github.com/android/ndk-samples/pull/803
Thank you very much for reporting issue and the fix!
