### ISSUE TITLE
Unable to make field private static final java.util.Map

### ISSUE THREAD

**Issue by nocsg** [android/ndk-samples#807]
Unable to make field private static final java.util.Map java.lang.ProcessEnvironment.theCaseInsensitiveEnvironment accessible: module java.base does not "opens java.lang" to unnamed module @1134affc

**Comment by ggfan** [comment]
may you provide more details for the issue? if this is a bug about SDK or java samples, please create a bug by following page: https://source.android.com/setup/contribute/report-bugs#bug-queues
