### ISSUE TITLE
Incorrect return type JNICALL, which should have been jstring. 

### ISSUE THREAD

**Issue by peerless2012** [android/ndk-samples#816]
When i clone this repo and open hello-libs

The jni metho in hello-libs.cpp has an error tips:
Incorrect return type JNICALL, which should have been jstring. 

AGP: 4.2.0

Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 27, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry: external.system.auto.import.disabled=true, ide.images.show.chessboard=true
Non-Bundled Plugins: com.github.kisstkondoros.codemetrics, com.intellij.marketplace, com.maaxgr.intellij.jsonviewer, name.kropp.intellij.makefile, org.toml.lang, com.thoughtworks.gauge, cn.wjdghd.unique.plugin.id, org.intellij.plugins.markdown

**Comment by DanAlbert** [comment]
It's a long on both ends now, so the sample is correct. Presumably the bug was fixed a while ago.
