### ISSUE TITLE
Error when compiling webp project (CMake Error at CMakeLists.txt:37 (add_subdirectory): add_subdirectory given source)

### ISSUE THREAD

**Issue by Mik-el** [android/ndk-samples#817]
Hi, I've successfully compiled the "native-media" project, but I can't compile the "webp" one.
I get this error:

`CMake Error at CMakeLists.txt:37 (add_subdirectory):
add_subdirectory given source
"C:/Users/Mikel/Desktop/ndk-samples-main/webp/libwebp" which is not an
existing directory.`

Since the "libwebp" subdirectory is missing from the project folder, I tried making one from file explorer, but this seems to generate more problems.

If needed, this is my configuration:

- ndkVersion version 22.1.7171670
- cMake version 3.18.1

How can I solve this?

**Comment by DanAlbert** [comment]
It works now, so assuming obsolete.
