### ISSUE TITLE
是否仍会创建java虚拟机?

### ISSUE THREAD

**Issue by 3ystem** [android/ndk-samples#829]
1. 如果使用纯native开发, 那么在应用启动时是否仍会创建java虚拟机?
2. 如果使用纯native开发, 是否可以通过jni调用为java封装的api?

**Comment by ggfan** [comment]
It is all java when come to framework API, may you clarify what do you mean by  the "pure native" way? (it is not about using the NativeActivity as Teapot samples in this repo, correct?)

**Comment by 3ystem** [comment]
> It is all java when come to framework API, may you clarify what do you mean by the "pure native" way? (it is not about using the NativeActivity as Teapot samples in this repo, correct?)

我指的是这个, https://github.com/android/ndk-samples/tree/main/native-activity

**Comment by ggfan** [comment]
It is a wrapper for the java class [NatvieActivity](https://developer.android.com/reference/android/app/NativeActivity), answers the 1st question.  To use other java side of APIs, derive a class from the NativeActivity, put it into the AndroidManifest.xml file as the startup activity, from there all Java APIs are accessible; from JNI side, you can call back the functions in your derived NativeActivity.  Teapot samples do that, you may have a look.

**Comment by 3ystem** [comment]
> 



> It is a wrapper for the java class [NatvieActivity](https://developer.android.com/reference/android/app/NativeActivity), answers the 1st question. To use other java side of APIs, derive a class from the NativeActivity, put it into the AndroidManifest.xml file as the startup activity, from there all Java APIs are accessible; from JNI side, you can call back the functions in your derived NativeActivity. Teapot samples do that, you may have a look.

谢谢你的解答, 起初我对"native activity"存在歧义

**Comment by zhiji-0424** [comment]
这个就是一个Java类, Android会启动这个类，然后这个类会加载native-lib。![Screenshot_2022_0225_205952.png](https://user-images.githubusercontent.com/96622419/155719604-e70c1bd7-8146-4e53-81e3-71c12cd5de82.png)

**Comment by zhiji-0424** [comment]
所以Java虚拟机仍然会被创建。
你可以继承这个类添加其他功能，比如：弹出输入法键盘，然后用Jni调用这个功能。

**Comment by ggfan** [comment]
correct.  the native lib name is up to you, just plug it into your manifest file, similar to [this](https://github.com/android/ndk-samples/blob/82d1af2cc423d1d2d5aa95f9c8fc829d4357bef9/native-activity/app/src/main/AndroidManifest.xml#L22).  NativeActivity has its limitations, might lag some features you might need; GameActivity seems to be built on the top of NativeActivity, you might have a look at [that](https://developer.android.com/games/agdk/integrate-game-activity) and confirm by yourself. On Android there is no such things as the pure C/C++ application, unless you do not want to use any of framework APIs(directly uses the underneath  bare bone linux); in that sense, you are not creating android apps.
