### ISSUE TITLE
UnsatisfiedLinkErrror in curl-ssl project

### ISSUE THREAD

**Issue by mrAbra** [android/ndk-samples#837]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.curlssl, PID: 18288
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libcurl.so" not found: needed by /data/app/~~d9uCC7TcZ2RntKJQEKLh1Q==/com.example.curlssl-ouZHa-fjvy4WRuJokQxvSA==/lib/x86/libapp.so in namespace classloader-namespace
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.example.curlssl.MainActivity.<clinit>(MainActivity.kt:45)
![Снимок](https://user-images.githubusercontent.com/35962429/158377228-0431192d-7837-4f80-8484-01e457a5c057.PNG)

**Comment by mrAbra** [comment]
If im roll back android studio to Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: ASM Bytecode Viewer Support Kotlin, com.birbit.artifactfinder

my apk my apk starts including all needed libraries
![Снимок](https://user-images.githubusercontent.com/35962429/158577345-71a5d3ba-e7f1-4624-9b83-3ff43c2cf8d8.PNG)

**Comment by DanAlbert** [comment]
Working for me. Presumably was an issue with that version of Android Studio, and is fixed on newer versions?
