### ISSUE TITLE
Looks like the CI build is failing with ```Could not determine artifacts for com.github.bumptech.glide:glide:4.11.0: Skipped due to earlier error```

### ISSUE THREAD

**Issue by HamzahussainInocent** [android/ndk-samples#840]
Looks like the CI build is failing with ```Could not determine artifacts for com.github.bumptech.glide:glide:4.11.0: Skipped due to earlier error```

_Originally posted by @dturner in https://github.com/android/uamp/issues/474#issuecomment-1014737697_

**Comment by DanAlbert** [comment]
Not any more.
