### ISSUE TITLE
hello-jni README:  "Sync project with gradle files" is on the File menu, at least on Mac

### ISSUE THREAD

**Issue by dneto0** [android/ndk-samples#845]
One of the steps in https://github.com/android/ndk-samples/tree/main/hello-jni/README.md says

> Click Tools/Android/Sync Project with Gradle Files.

On Mac at least, "Sync Project with Gradel Files" is on the File menu, not on the Tools menu.

**Comment by androiddevspartha** [comment]
Sample needs

**Comment by DanAlbert** [comment]
https://github.com/android/ndk-samples/pull/1012
