### ISSUE TITLE
I want to compile a bluetooth executable using ndk-build without any java language

### ISSUE THREAD

**Issue by accsky** [android/ndk-samples#848]
Hi. I want to compile with ndk-build without any java language. The purpose is to generate a native executable program. However, the linux dynamic link library used when compiling the bluetooth module does not support armV8, which causes the compilation to fail. Excuse me, can ndk-build compile bluetooth directly, and if so, where can I find the required header files and dynamic link libraries.

**Comment by DanAlbert** [comment]
You can't. The Android Framework is Java. Even if NDK APIs existed for Bluetooth (they don't), you need to call them from within an app, not an executable, because only apps have access to the framework.
