### ISSUE TITLE
timestamp of camera and IMU

### ISSUE THREAD

**Issue by jianchong-chen** [android/ndk-samples#851]
I used NDK API to get the camera & IMU sensor data(including timestamp) simultaneously.
But it seems that the timestamps of camera and IMU are **_NOT from a same clock system_**.
So is there some way to get the 2 sensor's timestamp that are synchronous completely？
Thanks！

**Comment by studyHooligen** [comment]
hi，did you solve the problem?

**Comment by DanAlbert** [comment]
This sounds more like an OS bug? You'd need to file that against the framework at http://b.android.com
