### ISSUE TITLE
How to exclude third party so when use gradle(version > =4.0) and cmake build library project?

### ISSUE THREAD

**Issue by Meinkonone** [android/ndk-samples#853]
[Google API Doc](https://developer.android.com/studio/projects/gradle-external-native-builds)

from doc, I know that if I want Include prebuilt native libraries, I should add src/main/jniLibs/ABI directory when use  Android Gradle Plugin prior to 4.0！

My project is a library project！

I am using Android Gradle Plugin >=4.0, and I want **exclude** my prebuilt native libraries。Even thought I have remove src/main/jniLibs/ABI director， but when build the aar file， it still include the prebuilt native libraries！

**Comment by Meinkonone** [comment]
I found that:
Use packagingOptions { exclude } can fix this!

**Comment by buffyanamin** [comment]
If you have many shared libraries to exclude, try `pickFirst` the library you wanted to include, then exclude other libraries.

see algorithm part in:  https://google.github.io/android-gradle-dsl/2.3/com.android.build.gradle.internal.dsl.PackagingOptions.html
