### ISSUE TITLE
How to load native library download from network?

### ISSUE THREAD

**Issue by TUT-jiayou** [android/ndk-samples#857]
Hi,all 
* I have a liba.so dynamic library request libb.so dynamic library. The libb.so library are downloaded from network. The libb.so is not saved in the path search by `dlopen` api. So, the libraries can not load successfully. 
* I want to know how to load the library downloaded form network. 
* Please give me more guide.
* Thanks for your help.

**Comment by TUT-jiayou** [comment]
* can the linker-namespace be a solution ?
 https://source.android.com/docs/core/architecture/vndk/linker-namespace

**Comment by ggfan** [comment]
Most likely you will have to do some research yourself on this:  the popular model is that the apk's includes those libs, dlopen() will search into the installed path.  Now for arbitrary path, you might try it out; and not sure it would conflict with device security thing.

**Comment by TUT-jiayou** [comment]
@ggfan 
thanks, would I keep the issue open as the my search record?

**Comment by ggfan** [comment]
Probably do a trial about with full path when doing dlopen(); then look at the dlopen() source code. Looks like your lib is for run-time dependency, not a compile dependent, otherwise you could not build your liba.  Probably close this one.

**Comment by TUT-jiayou** [comment]
* I try to use `dlopen` to add all the dependent libraries, and then add the dynamic library that implements my header file.
* I need to get the dependencies of dynamic library by parsing the `ELF` file format.  Do you have related recommended libraries？
* Thanks for your time.
