### ISSUE TITLE
[native-codec]need asynchronous demo

### ISSUE THREAD

**Issue by shuziyun** [android/ndk-samples#859]
native codec demo needs asynchronous demo for reference;

When I use asynchronous mode for decoding, I found that if I call the Amediacodec_queueInputBuffer() in the onAsyncInputAvailable callback, I cannot get the return of the function, and the subsequent process is blocked, what is the reason for this?

**Comment by shuziyun** [comment]
Amediacodec_queueInputBuffer shouldn't be called in onAsyncInputAvailable callback

**Comment by letterxy** [comment]
So how do you solve this problem? Where should Amediacodec_queueInputBuffer be called?
