### ISSUE TITLE
Does the Teapot activity need updating? Linting issues?

### ISSUE THREAD

**Issue by GOOG-sergiu** [android/ndk-samples#871]
Hi there, 

I am not sure if I am doing something wrong, but it looks like the Teapot activity (which none of the PRs touched) causes some issues on new PRs? Looks like linting issues?

https://github.com/android/ndk-samples/actions/runs/3567772665/jobs/5996607992
https://github.com/android/ndk-samples/actions/runs/3540274573/jobs/5972268390

(I would fix myself, but I cannot replicate this locally)

```
Note: /home/runner/work/ndk-samples/ndk-samples/teapots/classic-teapot/src/main/java/com/sample/teapot/TeapotNativeActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':classic-teapot:dexBuilderDebug'.
> Metaspace
```

**Comment by DanAlbert** [comment]
_Everything_ needs updating :( I'm going to close this because in general the whole repo needs an audit, and that's obvious enough that I don't think I need to track individual issues.
