### ISSUE TITLE
[camera] .onImageAvailable is not called for executable

### ISSUE THREAD

**Issue by Dan-YK** [android/ndk-samples#924]
Hello,

I was able to get basic camera applications to work successfully. When running android_main under the application, I see it calling .onImageAvailable after the capture. Afterward, I stripped a lot of code off to a bare minimum.

I tried to do the same for a standalone cpp executable (int main) using root.

I'm able to open the camera and capture and everything, but .onImageAvailable is not called at the end.

I'm assuming there is something special about the way the application utilizes the camera that allows it to call .onImageAvailable.

Does a standalone executable have the capability to capture a picture?

Thanks

**Comment by DanAlbert** [comment]
No, standalone executables have no access to the Android Framework. You have to make an app to do app things. Standalone executables are typically only useful for building debug tools like strace.
