### ISSUE TITLE
Setting the minimum sdk version

### ISSUE THREAD

**Issue by timprepscius** [android/ndk-samples#937]
Hey there,

I'm trying to set the minimum sdk version of the hello-vulkan project.
Doing things the internet suggests.  None work.

What is the simplest way to set the minimum version sdk for the hello vulkan project?

Thanks!

**Comment by DanAlbert** [comment]
You haven't told me what you tried, so I don't know what to tell you other than to edit https://github.com/android/ndk-samples/blob/9fa98672ff5e7fcfe53205bd276429ee0ecfcf0a/hello-vulkan/app/build.gradle#L29
