### ISSUE TITLE
Vulkan availability on a phone

### ISSUE THREAD

**Issue by timprepscius** [android/ndk-samples#938]
Hey there,

I'm trying to get the hello-vulkan running.  

I'm seeing something like this:
```
04-11 08:53:50.339 18535 18535 W android.hellov: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
04-11 08:53:50.350 18535 18535 I GameActivity: Looking for library libmain.so
04-11 08:53:50.352 18535 18535 I GameActivity: Application should have loaded the native library libmain.so explicitly by now. 
04-11 08:53:50.367 18535 18535 D GameActivity: GameActivity_register
04-11 08:53:50.491 18535 18560 I hellovkjni: Called - APP_CMD_INIT_WINDOW
04-11 08:53:50.589 18535 18554 I Adreno  : QUALCOMM build                   : ce5aeb9, I750f7f2fa6
04-11 08:53:50.589 18535 18554 I Adreno  : Build Date                       : 03/24/17
04-11 08:53:50.589 18535 18554 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.03
04-11 08:53:50.589 18535 18554 I Adreno  : Local Branch                     : mybranch25481872
04-11 08:53:50.589 18535 18554 I Adreno  : Remote Branch                    : quic/LA.BF64.1.2.3_rb1.11
04-11 08:53:50.589 18535 18554 I Adreno  : Remote Branch                    : NONE
04-11 08:53:50.589 18535 18554 I Adreno  : Reconstruct Branch               : NOTHING
04-11 08:53:50.619 18535 18560 I hellovkjni: Called - APP_CMD_INIT_WINDOW
04-11 08:53:50.620 18535 18560 I hellovkjni: Setting a new surface
04-11 08:53:50.621 18535 18560 I hellovkjni: Starting application
04-11 08:53:50.622 18535 18560 E vndksupport: Could not load vulkan.msm8992.so from default namespace: dlopen failed: library "vulkan.msm8992.so" not found.
04-11 08:53:50.623 18535 18560 D vulkan  : searching for layers in '/data/app/~~p93HyeoN8nvuCrVzJ4xLsA==/com.android.hellovk-8fnqMZJU-lOVU5py2963GA==/lib/arm64'
04-11 08:53:50.624 18535 18560 D vulkan  : searching for layers in '/data/app/~~p93HyeoN8nvuCrVzJ4xLsA==/com.android.hellovk-8fnqMZJU-lOVU5py2963GA==/base.apk!/lib/arm64-v8a'
04-11 08:53:50.628 18535 18560 I hellovkjni: available extensions
04-11 08:53:50.629 18535 18560 I hellovkjni: 	 VK_KHR_surface
04-11 08:53:50.629 18535 18560 I hellovkjni: 	 VK_KHR_android_surface
04-11 08:53:50.629 18535 18560 I hellovkjni: 	 VK_EXT_swapchain_colorspace
04-11 08:53:50.629 18535 18560 I hellovkjni: 	 VK_KHR_get_surface_capabilities2
04-11 08:53:50.629 18535 18560 I hellovkjni: 	 VK_EXT_debug_report
04-11 08:53:50.631 18535 18560 F libc    : /project/app/src/main/cpp/hellovk.h:849: void vkt::HelloVK::pickPhysicalDevice(): assertion "deviceCount > 0" failed
04-11 08:53:50.631 18535 18560 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18560 (android.hellovk), pid 18535 (android.hellovk)

```

It's on a "Robin" phone Android version 11
lineageOS API level, llama (9)

Should this phone be able to run vulkan?

How can I tell?

The android ecosystem is sort of like Win32 from 1994.  I can't tell what is going on anywhere.

Thanks,

-tim

**Comment by hybcloud** [comment]
And after that you can find that you can run the app by simply clicking it on your device, which makes it more confusing

**Comment by DanAlbert** [comment]
I think that crash is your answer? tbh it looks like a device bug rather than intentionally missing. In any case, it's something you have to report to the manufacturer.

**Comment by timprepscius** [comment]
Thank you for replying a year later.  Yes, the phone didn't support Vulkan.  Actually a whole bunch of other phones claim to support android, but actually don't.  If you are coming to this comment from DuckDuckGo, because you are trying to figure out if you should use Vulkan to support both iOS and Android, you will find out that Vulkan is probably not be worth it.

Also, strangely, this really blew my mind - OpenGLES can have better performance in some situations than Metal on iOS - how is this possible, no idea - I thought on iOS OpenGLES was being essentially layered over Metal.

**Comment by DanAlbert** [comment]
Sorry for the delay, but there wasn't anyone available to work on the samples for a while. I'm here now. That's the best I can do without a time machine.

**Comment by timprepscius** [comment]
If you had a time machine, I think some other items would take slightly higher priority. :-)

I assume you work for Google.  If you have the ability to make an app which a vendor could use to definitively test whether Vulkan works or not, that would be great.

As in- they could run it for development checking, and I could run it for sanity.  It would give a listing of *everything* that works and everything that doesn't work.


For instance, this app would test things like:
1. Can you even instantiate Vulkan.  Some phones which say they can do vulkan can't even do this.
2. Can you make a shader
3. Can you draw a triangle.
4. Can you write something like:  gl_Position.x = 5.0;
5. Can you write something like: gl_Position.x = 1.0; float v = 1.0; gl_Position.x = gl_Position.x + v;
6. Can you write something like: int a = (int)5.0; (but with variables to avoid optimization)
7.  Can you write something like int a = 10 % 3; (but using variables to avoid optimization)
8. Can you have an int in the vertex attributes
9. Can you have an int in the push constants
10. Can you have a short int etc etc, if you can't, does it fail with the extension


You get the point, it needs to test *everything* ad nauseum.

Then after this, you should do calls for shaders that are known to fail on some phones.
Make a big test suite of , "instantiate program, run program with given buffers, check result."


Having this app could have saved me:
1.  A hundred hours, attempting to "fix" vulkan shaders to run on android.
2. Helping me decide to jetison Vulkan on Android, as it's a waste of time.  This would have saved me a few weeks.


If you don't work for Google, you can completely ignore everything I just wrote.
