### ISSUE TITLE
Android Studio symbols issues

### ISSUE THREAD

**Issue by Hyphaed** [android/ndk-samples#940]
That's Android Studio Flamingo 2022.2.1 :: anyone can tell me why that's happening?  it seems the App is missing fonts

I'm on PopOS 22.04 LTS

![Screenshot from 2023-04-16 11-05-02](https://user-images.githubusercontent.com/19622367/232336538-539f17a2-8acc-4f0f-84b9-979c1b417747.png)

**Comment by DanAlbert** [comment]
Wrong bug tracker. This is the NDK samples. http://b.android.com.

**Comment by Hyphaed** [comment]
I'm on much better OS configuration nowadays

Ubuntu 24.04, custom kernel, some stuff built from source

using Android Studio Jellyfish | 2023.3.1

without problems

thanks anyway to check the issue
