### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by lmaddox** [android/ndk-samples#944]
Android 12 Termux

./gradlew clean build || sdkmanager 'build-tools;30.0.3'                          Warning: Dependant package with key emulator not found!                                                         FAILURE: Build failed with an exception.                                                                        * What went wrong:                                      Could not determine the dependencies of task ':app:lintVitalReportRelease'.                                     > Failed to install the following SDK components:             build-tools;30.0.3 Android SDK Build-Tools 30.0.3   Install the missing components using the SDK manager in Android Studio.                                                                                                                                                       * Try:                                                  > Run with --stacktrace option to get the stack trace.  > Run with --info or --debug option to get more log output.                                                     > Run with --scan to get full insights.                                                                         * Get more help at https://help.gradle.org                                                                      BUILD FAILED in 4s                                      Loading package information...                          Loading local repository...                             [                                       ] 3% Loading loc[                                       ] 3% Fetch remot[=                                      ] 3% Fetch remot[=                                      ] 4% Fetch remot[=                                      ] 5% Fetch remot[==                                     ] 5% Fetch remot[==                                     ] 6% Fetch remot[==                                     ] 7% Fetch remot[==                                     ] 7% Computing u[===                                    ] 8% Computing u[===                                    ] 10% Computing                                                         Warning: Dependant package with key emulator not found! [===                                    ] 10% Computing                                                         Warning: Unable to compute a complete list of dependencies.                                                     [===                                    ] 10% Computing

**Comment by SWAMIADITYA** [comment]
added the below line in the app's gradle properties in the android tag

buildToolsVersion "30.0.2"

**Comment by DanAlbert** [comment]
Not enough information. What sample are you talking about?
