### ISSUE TITLE
build.md not found in ndk/guides/graphics/getting-started

### ISSUE THREAD

**Issue by goofyseeker311** [android/ndk-samples#990]
https://developer.android.com/ndk/guides/graphics/getting-started
points to 
https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#android
build.md which is no longer that, its 404 not found.

new address is: https://github.com/KhronosGroup/Vulkan-Samples/blob/main/docs/build.adoc

also android-studio-2023.2.1.23-windows fails to close the hello-jni application window with stop button.
it will stay on background as a window, which needs to be program-button->closed separately.
stop debug button should close the application completely.

as a side note, why does an IDE need to setup any environment variables. defeats the purpose of integrated development environment (all included, even environment variables). seems like a sparse development environment. must be self-contained.

**Comment by DanAlbert** [comment]
> also android-studio-2023.2.1.23-windows fails to close the hello-jni application window with stop button.
it will stay on background as a window, which needs to be program-button->closed separately.
stop debug button should close the application completely.
>
> as a side note, why does an IDE need to setup any environment variables. defeats the purpose of integrated development environment (all included, even environment variables). seems like a sparse development environment. must be self-contained.

You're talking to the wrong people. File a bug against Android Studio: http://b.android.com

**Comment by DanAlbert** [comment]
The doc bug is also file in the wrong place: https://source.android.com/docs/setup/contribute/report-bugs#documentation

That's something that is actually in my power to fix though, so I sent the CL to do that. Please file doc bugs against the docs in the future though.
